export const weeks = [
 {n:1,start:'2026-09-21',end:'2026-09-27',title:'Das Fundament',subtitle:'Wörter, Sprachen, RegEx & DEA',hours:8,tasks:'Aufgaben 1–3 und 4a/c; 4b/d besprechen.',goal:'8 von 10 Checkfragen und zwei selbst gebaute DEAs.',topics:['Grundbegriffe & Komplexität','Sprachoperationen','Reguläre Ausdrücke','Deterministische Automaten']},
 {n:2,start:'2026-09-28',end:'2026-10-04',title:'Automaten verstehen',subtitle:'NEA, Potenzmenge & Minimierung',hours:8,tasks:'Aufgaben 5–8 und 4d.',goal:'Einen NEA umwandeln, einen DEA minimieren und Darstellungen übersetzen.',topics:['NEA & Potenzmengenkonstruktion','Minimierung','Reguläre Grammatik','Satz von Kleene']},
 {n:3,start:'2026-10-05',end:'2026-10-11',title:'Über Zustände hinaus',subtitle:'Grammatiken & Normalformen',hours:8,tasks:'Aufgaben 9, 11, 15, 17; Pumping ergänzen.',goal:'Zwei Grammatiken in CNF umformen und einen Syntaxbaum erstellen.',topics:['Grenzen regulärer Sprachen','Pumping-Idee','Syntaxbäume & Mehrdeutigkeit','Chomsky-Normalform']},
 {n:4,start:'2026-10-12',end:'2026-10-18',title:'Sprachen entschlüsseln',subtitle:'CYK, Parser & Kellerautomaten',hours:8,tasks:'Aufgaben 16 und 18; CYK-Vorlesungsbeispiel.',goal:'Zwei CYK-Tabellen mit Begründung lösen und den Parserbezug erklären.',topics:['CYK-Algorithmus','Ableitungen rekonstruieren','Kellerautomaten','Abschlusseigenschaften']},
 {n:5,start:'2026-10-19',end:'2026-10-25',title:'Die universelle Maschine',subtitle:'Turingmaschinen & Berechnung',hours:8,tasks:'Aufgaben 10, 12, 13; Aufgabe 10 später ergänzen.',goal:'Konfigurationen ausführen und einen TM-Algorithmus mit Testfällen entwerfen.',topics:['Kontextsensitive Sprachen','TM-Algorithmen','DTM & NTM','Einstieg P und NP']},
 {n:6,start:'2026-10-26',end:'2026-11-01',title:'Wie schwer ist schwer?',subtitle:'P, NP & Reduktionen',hours:8,tasks:'Aufgaben 19 und 20; 21 zur Vertiefung.',goal:'Zwei neue Situationen modellieren und die Bedeutung von NP erklären.',topics:['P und NP','Reduktionsrichtung','Graphenprobleme','Entscheiden vs. Optimieren']},
 {n:7,start:'2026-11-02',end:'2026-11-08',title:'Grenzen des Machbaren',subtitle:'Entscheidbarkeit & Simulation 1',hours:8,tasks:'Aufgaben 10 und 14. Am 07.11. die vollständige Altklausur.',goal:'Gesamten Stoff einmal bearbeitet; drei größte Lücken benannt.',topics:['Halteproblem','Satz von Rice','Chomsky-Hierarchie','Simulation 1 · 07.11.']},
 {n:8,start:'2026-11-09',end:'2026-11-15',title:'Wissen unter Beweis',subtitle:'Gemischtes Training & Simulation 2',hours:9,tasks:'22 „Minimierung DEA“ (S. 22), 22 „Turingmaschinen“ (S. 23), 23 „CYK“ (S. 24).',goal:'Mindestens 75 % der Übungspunkte und kein ausgelassener Kernbereich.',topics:['Gezielte Fehlerkorrektur','Neue Aufgabenvarianten','Gemischte Kurzfragen','Simulation 2 · 14.11.']},
 {n:9,start:'2026-11-16',end:'2026-11-20',title:'Bereit für den nächsten Schritt',subtitle:'Endspurt zur Klausur',hours:5,tasks:'17.11. neue Simulation; 18.11. letzte Lücken; 19.11. leichte Wiederholung.',goal:'Zwei zeitbegrenzte Durchläufe mit mindestens 80 %. Klausur am 20.11.',topics:['Simulation 3 · 17.11.','Letzte Fehler korrigieren','Leichte Wiederholung','Klausur · 20.11.']}
];
export const units = [
 {id:'bausteine',boss:'Der Symbolwächter',title:'Die Bausteine verstehen',subtitle:'Vom Problem zum ersten Wort',icon:'spark',lessons:['motivation','complexity','notation','alphabet','empty']},
 {id:'sprachen',boss:'Die Mengenhydra',title:'Mit Sprachen rechnen',subtitle:'Mengen, Verknüpfungen und Abschlüsse',icon:'layers',lessons:['languages','sets','concat','closure','quotient']},
 {id:'muster',boss:'Der Musterweber',title:'Muster beschreiben',subtitle:'Reguläre Ausdrücke lesen und konstruieren',icon:'code',lessons:['regex','construct']},
 {id:'automaten',boss:'Die Zustandsmaschine',title:'Automaten zum Leben erwecken',subtitle:'Lesen, merken, entscheiden',icon:'nodes',lessons:['dfa','parity','alternate','complement']},
 {id:'verbinden',boss:'Der Hierarchiehüter',title:'Das große Ganze verbinden',subtitle:'Grammatiken, Hierarchie und Transfer',icon:'orbit',lessons:['grammar','hierarchy','transfer']}
];
const l=(id,title,minutes,source,intro,sections,example,trap,reflection,lab)=>({id,title,minutes,source,intro,sections,example,trap,reflection,lab});
export const lessons = [
 l('motivation','Warum Theoretische Informatik?',8,'Skript W1 · S. 3–4',
 'Bevor du mit Symbolen rechnest, brauchst du eine Idee davon, welche Fragen wir überhaupt stellen.',
 [['Problem, Instanz, Algorithmus','Ein Problem ist die allgemeine Aufgabe, etwa „Sortiere eine Zahlenliste“. Eine Instanz ist eine konkrete Eingabe, etwa [7, 2, 5]. Ein Algorithmus ist ein präzises Verfahren, das solche Eingaben verarbeitet.'],['Drei unterschiedliche Fragen','Kann ich eine Aufgabe exakt beschreiben? Gibt es ein Verfahren, das jede Eingabe entscheidet? Wie viel Zeit und Speicher benötigt es? Beschreibbarkeit, Entscheidbarkeit und Aufwand sind verschiedene Fragen.'],['Warum Sprachen?','Quellcode, Kennungen und Protokollnachrichten sind Zeichenfolgen. Die Menge aller erlaubten Folgen ist eine formale Sprache. Syntax prüft den Aufbau: Ein korrekt formatiertes Kennzeichen muss deshalb noch nicht tatsächlich vergeben sein.']],
 ['Vom Alltag zum Wortproblem','Eine Zugangscode-Regel erlaubt genau vier Ziffern. „1234“ erfüllt die Syntax, „12a4“ nicht. Ob „1234“ einem Nutzer zugeordnet ist, ist eine weitere Frage.'],
 'Ein passendes Format bestätigt noch keine inhaltliche Bedeutung.',
 'Wähle ein Beispiel aus deinem Alltag. Was sind Problem, Instanz und eine mögliche Syntaxregel?'),
 l('complexity','Wie wächst der Aufwand?',12,'Skript W1 · S. 4',
 'Die Eingabegröße n verknüpft ein Verfahren mit seinem Aufwand.',
 [['Was zählt als n?','Bei einem Wort ist n häufig die Zahl seiner Zeichen, bei einer Liste die Zahl der Elemente. Bei einer Zahl zählt oft die Anzahl der Bits. Der Binärwert 1000 ist 8, seine Eingabelänge aber 4.'],['O-Notation','O beschreibt eine asymptotische obere Schranke. Bei T(n) = 3n + 7 dominieren für große n die linearen Anteile; T liegt in O(n). Konstanten und kleinere Terme beeinflussen den praktischen Aufwand trotzdem.'],['Zeit und Speicher trennen','Ein fester DEA liest n Zeichen in n Übergängen. Er braucht als zusätzlichen Speicher nur seinen aktuellen Zustand. Lineare Lesezeit und konstanter Zusatzspeicher passen also zusammen.']],
 ['Zehnmal größere Eingabe','Bei n → 10n wächst n um Faktor 10, n² um Faktor 100 und n³ um Faktor 1000. Für 2ⁿ ist der Faktor von n abhängig: 2¹⁰ⁿ / 2ⁿ = 2⁹ⁿ.'],
 'Zwei Schleifen bedeuten nur dann O(n²), wenn ihre tatsächlichen Durchläufe entsprechend wachsen. O(n) ist zudem keine exakte Schrittzahl.',
 'Warum kann ein Verfahren bei kleinen Eingaben schneller und bei großen Eingaben langsamer sein?', 'complexity'),
 l('notation','Zeichen wie Sätze lesen',10,'Skript W1 · S. 5–6',
 'Mathematische Notation ist eine präzise Kurzschrift. Übersetze sie zuerst in eigene Worte.',
 [['Element oder Teilmenge?','Bei L = {0, 10} gilt 10 ∈ L: Das Wort 10 ist ein Element. {10} ⊆ L bedeutet: Jedes Element dieser kleinen Menge liegt in L. ⊊ bezeichnet eine echte Teilmenge.'],['Mengen und Folgen','Mengen besitzen keine Reihenfolge und keine doppelten Elemente: {0, 0, 1} = {1, 0}. Wörter besitzen eine Reihenfolge: 01 ≠ 10. |A| zählt Mengenelemente; |w| zählt Zeichen eines Wortes.'],['Logik lesen','∀ bedeutet „für alle“, ∃ „es gibt mindestens eines“, ∧ „und“, ∨ „oder, auch beides“, ¬ „nicht“. P ⇒ Q ist eine Folgerung; P ⇔ Q verlangt beide Richtungen. ℕ₀ enthält 0.']],
 ['Eine Definition übersetzen','L = {w ∈ {0,1}* : |w| = 2} heißt: L enthält genau die Binärwörter mit Länge 2. Das sind 00, 01, 10 und 11.'],
 '01 ∈ L und {01} ⊆ L sprechen über unterschiedliche Arten von Objekten.',
 'Formuliere „w ∈ L ⇔ |w| = 2“ in einem vollständigen Satz.'),
 l('alphabet','Alphabet, Wort und Wortlänge',10,'Skript W1 · S. 7 und 9',
 'Ein Alphabet ist dein Zeichenvorrat. Ein Wort ist eine endliche Folge dieser Zeichen.',
 [['Alphabet Σ','Σ ist eine endliche Menge erlaubter Symbole, zum Beispiel {0,1}. Das Skript lässt auch das leere Alphabet zu.'],['Wort w','010 ist ein Wort über {0,1}, 012 nicht. Jedes Wort in Σ* ist endlich. Es gibt bei nichtleerem Alphabet trotzdem Wörter beliebig großer endlicher Länge.'],['Wortmengen und Potenzmenge','Σⁿ enthält genau die Wörter der Länge n. Bei k Symbolen sind es kⁿ Möglichkeiten; Σ⁰ = {ε}. Σ* enthält alle endlichen Längen. Die Potenzmenge P(Σ) enthält hingegen Teilmengen des Alphabets.']],
 ['Was gilt als ein Symbol?','Bei Σ = {Menschen, Leben, Tanzen, Welt} kann „Menschen“ ein einzelnes Token sein. „Menschen · Tanzen“ hat dann Länge 2. Bei einem Buchstabenalphabet wäre die Länge eine andere.'],
 'Σ* enthält unendlich viele endliche Wörter, keine unendlich langen Wörter. Die Definition des Alphabets entscheidet über die Länge.',
 'Warum sind P({0,1}) und {0,1}* verschieden? Gib jeweils zwei Elemente an.'),
 l('empty','ε, ∅ und {ε}',10,'Skript W1 · S. 8–9',
 'Drei ähnlich wirkende Schreibweisen – drei verschiedene Objekte.',
 [['Das leere Wort ε','ε ist eine Folge aus null Zeichen. |ε| = 0. Beim Anhängen verändert es nichts: uε = εu = u. Das Zeichen 0 ist dagegen ein Wort mit Länge 1.'],['Die leere Sprache ∅','∅ ist eine Menge ohne Wörter: |∅| = 0. Die Sprache {ε} enthält genau ein Wort, daher |{ε}| = 1.'],['Potenzen eines Wortes','Für u = 01 gilt u⁰ = ε, u¹ = 01 und u² = 0101. Verkettung ist assoziativ, aber im Allgemeinen nicht kommutativ: uv kann sich von vu unterscheiden.']],
 ['Eine leere Karte und eine leere Schachtel','Stell dir Wörter als beschriftete Karten vor. ε ist eine unbeschriftete Karte. {ε} ist eine Schachtel mit genau dieser Karte. ∅ ist eine Schachtel ohne Karte.'],
 'Eine Karte ohne Zeichen ist immer noch eine Karte. Entsprechend ist {ε} nicht leer.',
 'Erkläre, warum L · {ε} = L, aber L · ∅ = ∅ gilt.'),
 l('languages','Eine Sprache ist eine Wortmenge',10,'Skript W1 · S. 10 und 30',
 'L ⊆ Σ*: Eine formale Sprache wählt Wörter aus allen möglichen Wörtern aus.',
 [['Aufzählen oder beschreiben','L = {0,10,110} enthält genau drei Wörter. L = {w ∈ {0,1}* : w endet auf 1} enthält unendlich viele. Endliche Beschreibung und endliche Sprache sind verschiedene Eigenschaften.'],['Wortproblem','Gegeben sind L und ein Wort w. Die Frage lautet: Gilt w ∈ L? Bei „endet auf 1“ ist 101 enthalten, 100 nicht.'],['Die Reihenfolge zählt','Die Sprache aller Wörter mit gleich vielen 0 und 1 enthält auch 10. In {0ⁿ1ⁿ : n ∈ ℕ₀} stehen zuerst alle Nullen und dann alle Einsen. Beide Sprachen enthalten ε, sind aber verschieden.']],
 ['Eine Beschreibung zerlegen','{uav : u ∈ {a,b}*, v ∈ {a,b}}: Erst ein beliebiger Anfang u, dann ein a, dann genau ein letztes Symbol v. Das vorletzte Zeichen ist deshalb a; das Wort braucht mindestens zwei Zeichen.'],
 'Nicht jede formale Sprache hat automatisch eine Grammatik oder einen Automaten als Erkenner.',
 'Gib für „vorletztes Zeichen a“ zwei gültige und zwei ungültige Wörter an.'),
 l('sets','Vereinigung, Schnitt und Komplement',12,'Skript W1 · S. 11',
 'Sprachen sind Mengen. Also kannst du mit ihren Elementen Mengenoperationen ausführen.',
 [['Vereinigen und schneiden','A ∪ B enthält Wörter aus A oder B (auch aus beiden). A ∩ B enthält nur gemeinsame Wörter. In A ∖ B liegen Wörter aus A, die nicht in B sind. Doppelte Elemente werden nicht mehrfach gezählt.'],['Komplement braucht ein Alphabet','Lᶜ = Σ* ∖ L. Bei der Sprache „Binärwörter mit letzter 1“ enthält das Komplement alle Wörter mit letzter 0 und zusätzlich ε.'],['De Morgan','(A ∪ B)ᶜ = Aᶜ ∩ Bᶜ und (A ∩ B)ᶜ = Aᶜ ∪ Bᶜ. Beide Komplemente müssen sich auf dieselbe Grundmenge beziehen.']],
 ['Drei Fragen an dieselben Mengen','A = {0,01,1}, B = {01,10}. Zusammen: {0,01,1,10}. Gemeinsam: {01}. Nur links: {0,1}.'],
 'Das Komplement einer endlichen Sprache über nichtleerem Alphabet ist gewöhnlich unendlich. Eine kurze aufgezählte Liste wäre nicht vollständig.',
 'Warum gehört ε zum Komplement von „endet auf 1“?', 'sets'),
 l('concat','Sprachen verketten',12,'Skript W1 · S. 12 und 31',
 'Bei A · B wählst du ein Wort aus A, eines aus B und hängst sie in dieser Reihenfolge aneinander.',
 [['Alle Paare bilden','A · B = {uv : u ∈ A, v ∈ B}. Für A = {ε,0} und B = {1,01} entstehen 1, 01, 01 und 001. Als Menge bleibt {1,01,001}.'],['Anzahl der Ergebnisse','Für endliche Sprachen gilt |A · B| ≤ |A| · |B|. Verschiedene Paare können dasselbe Wort ergeben. Gleichheit gilt nur, wenn kein Ergebnis doppelt entsteht.'],['Rechenregeln','A · {ε} = A; A · ∅ = ∅. Die Verkettung ist assoziativ: (A · B) · C = A · (B · C). Außerdem gilt A · (B ∪ C) = (A · B) ∪ (A · C).']],
 ['Ein eindeutiges Produkt','L₀ = {ε,0,00,000}, L₁ = {ε,1,11}. Die Anzahl der Nullen und Einsen identifiziert jedes Paar eindeutig. Daher entstehen hier tatsächlich 4 · 3 = 12 verschiedene Wörter.'],
 'Vereinigung wählt vorhandene Wörter, Verkettung setzt Wörter zusammen. Beides ist etwas anderes.',
 'Finde zwei verschiedene Paare aus {ε,0} × {1,01}, die dasselbe Wort liefern.', 'sets'),
 l('closure','Stern und Plus richtig verstehen',12,'Skript W1 · S. 13',
 'Ein Abschluss erlaubt wiederholte Verkettungen. Entscheidend ist, ob auch null Wiederholungen erlaubt sind.',
 [['Potenzen von Sprachen','L⁰ = {ε}, L¹ = L, L² = L · L. Für L = {a,bb} ist L² = {aa,abb,bba,bbbb}. Zwei Faktoren bedeuten nicht automatisch zwei Zeichen.'],['Kleene-Stern L*','L* = L⁰ ∪ L¹ ∪ L² ∪ … . Null Wiederholungen sind erlaubt. Daher enthält L* immer ε. Jede einzelne Verkettung verwendet nur endlich viele Faktoren.'],['Positiver Abschluss L⁺','L⁺ beginnt bei L¹. Trotzdem kann ε dazugehören, wenn ε schon in L liegt. Es gilt L⁺ = L · L* und L* = {ε} ∪ L⁺.']],
 ['Vier Randfälle','∅* = {ε}; ∅⁺ = ∅; {ε}* = {ε}; {ε}⁺ = {ε}. Ohne auswählbare Wörter geht nur die Verkettung aus null Faktoren. Eine vorhandene leere Eingabe lässt sich dagegen beliebig oft verketten.'],
 '„Plus heißt ohne ε“ stimmt nur, wenn ε nicht schon in der Ausgangssprache liegt.',
 'Warum gehört a zu {a,b}*, aber nicht zu {ab}*?'),
 l('quotient','Rechtsquotient: Suffix entfernen',12,'Skript W1 · S. 14; Aufgabe 2',
 'A / B fragt nach Wörtern, die du mit einem passenden Endstück aus B zu einem Wort aus A ergänzen kannst.',
 [['Die Formel lesen','A / B = {w : ∃ z ∈ B mit wz ∈ A}. Gesucht ist w. Ein einziges passendes z genügt. Gleichwertig entfernst du ein vollständiges Suffix aus B am Ende eines Wortes aus A.'],['ε als Suffix','Jedes Wort endet auf das leere Wort. Entfernst du ε, bleibt das ursprüngliche Wort übrig. Ist ε ∈ B, gilt daher A ⊆ A / B.'],['Wann entsteht ε?','Genau wenn ein vollständiges Wort aus A zugleich in B liegt: εz = z. Bei endlichen Beispielen kannst du alle passenden Kombinationen systematisch auflisten.']],
 ['Originalaufgabe 2','A = {00,01,001}, B = {ε,0,1}. Entfernen von ε liefert 00,01,001. Entfernen von 0 aus 00 liefert 0. Entfernen von 1 aus 01 und 001 liefert 0 und 00. Ergebnis: {0,00,01,001}.'],
 'Im Aufgabenblatt heißt diese Operation irreführend „Durchschnitt“. Die Formel meint einen Rechtsquotienten, keinen Schnitt.',
 'Finde zwei nichtleere Sprachen A und B mit A / B = ∅.', 'sets'),
 l('regex','RegEx lesen: Was bindet zuerst?',12,'Skript W1 · S. 17–18 und 28',
 'Ein regulärer Ausdruck ist eine endliche Beschreibung. L(r) ist die damit beschriebene Sprache.',
 [['Die Bausteine','Ein Zeichen a beschreibt {a}, ε beschreibt {ε}, ∅ beschreibt die leere Sprache. Mit Vereinigung, Verkettung und Stern entstehen weitere Ausdrücke. In der App funktionieren ∪ und | als Alternative.'],['Die Reihenfolge','Zuerst Klammern, dann Stern/Plus, dann Verkettung, zuletzt Vereinigung. 01* bedeutet: eine 0, beliebig viele 1en. (01)* wiederholt dagegen ganze 01-Blöcke.'],['Das ganze Wort','Theoretische RegEx beschreiben die gesamte Eingabe. Eine Teilzeichenfolge genügt nicht. Erweiterungen wie Rückverweise gehören nicht zu diesen regulären Ausdrücken.']],
 ['Die Klammerfalle','(0 ∪ 1)*0 ∪ 1 beschreibt Binärwörter mit letzter 0 und zusätzlich das einzelne Wort 1. 01 ist nicht enthalten. (0 ∪ 1)*(0 ∪ 1) beschreibt dagegen alle nichtleeren Binärwörter.'],
 'Regulär bedeutet nicht endlich. 0* beschreibt unendlich viele Wörter mit einer endlichen Beschreibung.',
 'Finde ein Wort, das 01* akzeptiert und (01)* ablehnt.', 'regex'),
 l('construct','Deinen eigenen RegEx bauen',15,'Skript W1 · S. 19–20 und 35–38',
 'Zerlege die Bedingung in erlaubte Bausteine und prüfe anschließend beide Richtungen.',
 [['Pflichtzeichen und freie Bereiche','„Endet auf 01“: (0 ∪ 1)*01. Der Anfang ist frei, das Ende fest. „Genau zwei Einsen“: 0*10*10*. Die zwei ausgeschriebenen Einsen sind verpflichtend; die drei Zwischenbereiche dürfen nur Nullen beitragen.'],['Gerade oder höchstens eine','0*(10*10*)* liefert Einsen paarweise. 0*(ε ∪ 1)0* erlaubt höchstens eine 1. In beiden Sprachen ist ε enthalten.'],['Begründen und testen','Jedes erzeugte Wort muss die Bedingung erfüllen. Umgekehrt muss jedes erlaubte Wort erzeugbar sein. Teste ε, ein kurzes gültiges Wort und einen knapp ungültigen Fall.']],
 ['Vorletztes Zeichen 0','(0 ∪ 1)*0(0 ∪ 1): beliebiger Anfang, verpflichtende 0, genau ein beliebiges Schlusszeichen. 01 und 101 passen; 0 ist zu kurz.'],
 'Viele erfolgreiche Tests beweisen eine unendliche Sprachgleichheit noch nicht. Ein Gegenbeispiel widerlegt sie sofort. Das Labor nutzt einen vollständigen Automatenvergleich.',
 'Begründe für deinen Ausdruck „genau zwei Einsen“ beide Richtungen.', 'regex'),
 l('dfa','Ein DEA liest Zeichen für Zeichen',15,'Skript W1 · S. 21–22 und 25',
 'Ein deterministischer endlicher Automat speichert nur seinen aktuellen Zustand.',
 [['Die fünf Bestandteile','A = (Q, Σ, δ, s, F). Q ist die endliche Zustandsmenge, Σ das Alphabet, δ die Übergangsfunktion, s der Start und F die Menge akzeptierender Zustände. Für jeden Zustand und jedes Zeichen gibt es genau einen Übergang.'],['Ein Lauf','Starte bei s. Lies das nächste Zeichen, nutze δ und wechsle den Zustand. Wiederhole das bis zum Ende. Erst der Zustand nach dem gesamten Wort entscheidet, ob es akzeptiert wird.'],['Die leere Eingabe','Bei ε gibt es keinen Übergang. Daher wird ε genau dann akzeptiert, wenn der Startzustand in F liegt.']],
 ['Endet auf 1','Zustand A bedeutet „Anfang oder zuletzt 0“, B bedeutet „zuletzt 1“. Bei 0 geht jeder Zustand nach A, bei 1 nach B. Nur B akzeptiert. 101 läuft A → B → A → B und wird angenommen; 10 endet in A.'],
 'Ein Endzustand ist kein Stoppbefehl. Nach einer 1 kann noch eine 0 folgen und die Annahme wieder verloren gehen.',
 'Warum reichen für „endet auf 1“ zwei Zustände?', 'dfa'),
 l('parity','Was muss ein Zustand wissen?',12,'Skript W1 · S. 23 und 26',
 'Gute Zustände haben eine Bedeutung: Sie merken sich genau die Information, die später noch benötigt wird.',
 [['Gerade und ungerade','Für „gerade Anzahl Einsen“ reichen G und U. Eine 1 wechselt G ↔ U. Eine 0 verändert nichts. Start ist G, denn null ist gerade. Nur G akzeptiert.'],['Begrenzt merken, unbegrenzt lesen','Der Automat kann beliebig lange Wörter lesen. Er merkt sich trotzdem nie die genaue Anzahl der Einsen, sondern nur den Rest bei Division durch 2.'],['Wann reicht das nicht?','Für {0ⁿ1ⁿ : n ∈ ℕ₀} muss eine beliebig große Anzahl später genau verglichen werden. Endlich viele Zustände können diese unbeschränkte Information nicht speichern. Das ist die Intuition; ein formaler Beweis folgt später.']],
 ['Ein Lauf mit vier Einsen','101101 enthält vier Einsen. Die Zustände sind G → U → U → G → U → U → G. Das Wort wird akzeptiert.'],
 'Unendlich viele gültige Wörter bedeuten nicht „nicht regulär“: 0* und die Paritätssprache sind Gegenbeispiele.',
 'Warum ist „gerade viele“ leichter zu speichern als „genau gleich viele“?', 'dfa'),
 l('alternate','Deinen ersten DEA konstruieren',15,'Skript W1 · S. 24, 26 und 32; Aufgabe 4a',
 'Wir bauen einen Automaten für Binärwörter ohne 00 und ohne 11.',
 [['Erst die Zustandsbedeutung','S = noch nichts gelesen; A = gültig und zuletzt 0; B = gültig und zuletzt 1; X = Wiederholung gefunden. S, A und B akzeptieren.'],['Übergänge entwickeln','Von S führt 0 nach A und 1 nach B. Von A führt 1 nach B, aber 0 nach X. Von B führt 0 nach A, aber 1 nach X. X bleibt auf beiden Zeichen X.'],['Konstruktion prüfen','Alphabet → ε prüfen → notwendige Information → Zustände → alle Übergänge → Endzustände → Grenzfälle. Ein Fehlerzustand macht die Funktion vollständig.']],
 ['Endliche Wortlisten','Für {do,double,catch,case} kann ein Automat das bisher gelesene Präfix speichern. „do“ ist bereits akzeptierend, aber auch ein Anfang von „double“. Unpassende Zeichen führen in den Fehlerzustand.'],
 'ε hat keine gleichen Nachbarn und wird hier akzeptiert. Die wörtliche Bedingung ist maßgeblich, auch wenn eine Folienzeichnung ε auslässt.',
 'Konstruiere den Automaten ohne Vorlage. Warum kann X nicht wieder verlassen werden?', 'builder'),
 l('complement','Den Komplementautomaten bauen',12,'Skript W1 · S. 27 und 38; Aufgabe 4c',
 'Das Komplement soll genau die zuvor abgelehnten Wörter akzeptieren.',
 [['Zuerst vollständig machen','Jeder Zustand braucht für jedes Symbol genau einen Folgezustand. Fehlende Übergänge ergänzt du mit einem Fehlerzustand; dieser hat alle Übergänge zu sich selbst.'],['Dann Endzustände tauschen','Ersetze F durch Q ∖ F. Alphabet, Zustände, Start und Übergänge bleiben gleich. Auch ein ursprünglicher Fehlerzustand wird dabei akzeptierend.'],['Warum ist das richtig?','Jedes Wort endet in genau einem Zustand. Dieser liegt entweder in F oder in Q ∖ F. Genau einer der beiden vollständigen DEAs akzeptiert also das Wort.']],
 ['Aufgabe 4c','Q = {q0,q1,q2,q3,err}, F = {q0,q1}. Das Komplement hat Fᶜ = {q2,q3,err}. ε bleibt im Start q0 und wird im Komplement abgelehnt. 0 endet in err und wird jetzt akzeptiert.'],
 'Die beiden Automaten unterscheiden sich in der Akzeptanz, nicht darin, ob sie anhalten. Ein vollständiger DEA verarbeitet jedes endliche Wort.',
 'Warum ist „nur die sichtbaren Doppelkreise vertauschen“ bei fehlenden Kanten gefährlich?', 'dfa'),
 l('grammar','Grammatiken erzeugen Wörter',12,'Skript W1 · S. 15 und 30',
 'Eine Grammatik erzeugt gültige Wörter. Ein Automat prüft ein schon gegebenes Wort.',
 [['Terminale und Variablen','G = (Σ,V,S,R). Σ enthält Zeichen des fertigen Wortes. V enthält Variablen (Platzhalter), S ∈ V ist die Startvariable, R die Regelmenge. Σ und V sind disjunkt.'],['Schrittweise ersetzen','Mit S → 0S und S → 1 ergibt sich S ⇒ 0S ⇒ 00S ⇒ 001. Erst wenn keine Variablen mehr übrig sind, ist ein fertiges Wort entstanden.'],['Dasselbe aus drei Perspektiven','Die Grammatik erzeugt {0ⁿ1 : n ∈ ℕ₀}. Der RegEx 0*1 beschreibt dieselbe Sprache. Ein passender DEA erkennt genau diese Wörter.']],
 ['Null Wiederholungen sind möglich','Wende sofort S → 1 an. So entsteht 1. Zwei Anwendungen von S → 0S und anschließend S → 1 erzeugen 001. 00S ist eine Zwischenform, kein Terminalwort.'],
 'Der Pfeil in einer Regel beschreibt eine Ersetzung. Er ist kein Zeichen, das später in der Eingabe stehen soll.',
 'Gib eine Ableitung von 0001 an und erkläre, warum 10 nicht entsteht.'),
 l('hierarchy','Die Chomsky-Hierarchie einordnen',12,'Skript W1 · S. 16',
 'Mehr erlaubte Grammatikregeln und mehr Speicher ermöglichen ausdrucksstärkere Modelle.',
 [['Typ 3: regulär','Endliche Automaten; zum Beispiel rechtslineare Regeln A → aB oder A → a (ε je nach Konvention). Beispiel: Binärwörter mit letzter 1.'],['Typ 2: kontextfrei','Links steht genau eine Variable: A → u. Ein nichtdeterministischer Kellerautomat besitzt zusätzlich einen Stack. {0ⁿ1ⁿ : n ≥ 0} ist kontextfrei und nicht regulär.'],['Typ 1 und Typ 0','Typ 1: nichtverkürzende Regeln mit möglicher ε-Sonderregel; nichtdeterministische linear beschränkte TM. Beispiel: {aⁿbⁿcⁿ}. Typ 0: allgemeine Grammatik und TM als Erkenner; bei Nichtzugehörigkeit muss sie nicht halten.']],
 ['Verschachtelte Klassen','Regulär ⊊ kontextfrei ⊊ kontextsensitiv ⊊ Typ 0. Jede kleinere Klasse liegt vollständig in den größeren. Eine reguläre Sprache ist also auch kontextfrei.'],
 '„Nicht regulär“ bedeutet nicht automatisch „kontextfrei“. Und nicht jede Typ-0-Sprache ist unentscheidbar. Eine pauschale O-Zeit pro Hierarchiestufe wäre unpräzise.',
 'Welchen zusätzlichen Speicher brauchst du für beliebig tief geschachtelte Klammern?'),
 l('transfer','Begründen statt wiedererkennen',15,'Skript W1 · S. 28–29 und 33',
 'Eine gute Lösung zeigt nicht nur ein Ergebnis, sondern auch, warum genau die verlangte Sprache entsteht.',
 [['Jede endliche Sprache ist regulär','Schreibe jedes enthaltene Wort als Verkettung seiner Zeichen und verbinde die Wörter mit ∪. Die Fälle ε und ∅ haben eigene Grundausdrücke.'],['Abgeschlossenheit und Äquivalenz','Reguläre Sprachen sind unter Vereinigung, Schnitt, Komplement, Differenz, Verkettung und Stern abgeschlossen. Für Schnitt hilft A ∩ B = (Aᶜ ∪ Bᶜ)ᶜ. RegEx, DEA, NEA und reguläre Grammatik beschreiben dieselbe Klasse.'],['Die Primzahl-Falle','„Akzeptiert alle Primzahlen“ verlangt allein noch nicht, Nichtprimzahlen abzulehnen. Ein Automat, der alles akzeptiert, erfüllt diese schwache Bedingung, ist aber kein Primzahlprüfer. „Genau alle“ verlangt beide Richtungen.']],
 ['Kleene hat zwei Richtungen','RegEx → passender Automat und Automat → passender RegEx. Der Weg über NEA, Potenzmengenkonstruktion und Zustandselimination folgt in Woche 2.'],
 'Ein Automat, der alles akzeptiert, erkennt nicht jede Teilmenge davon. „Enthält alle erlaubten Wörter“ reicht für eine korrekte Sprachbeschreibung nicht.',
 'Erkläre mit De Morgan, warum der Schnitt zweier regulärer Sprachen regulär ist.')
];
export const lessonById = Object.fromEntries(lessons.map(l=>[l.id,l]));

const q=(id,lesson,prompt,options,answer,explanation,hint)=>({id,lesson,type:'choice',prompt,options,answer,explanation,hint:hint||'Übersetze die Bedingung in eigene Worte und prüfe besonders den kleinsten Fall.'});
const s=(id,lesson,prompt,answer,explanation,hint)=>({id,lesson,type:'set',prompt,answer,explanation,hint:hint||'Bilde alle möglichen Ergebnisse. Streiche Doppelungen und prüfe ε.'});
const n=(id,lesson,prompt,answer,explanation,hint)=>({id,lesson,type:'number',prompt,answer,explanation,hint:hint||'Setze die Werte Schritt für Schritt in die Regel ein.'});
const r=(id,prompt,answer,explanation)=>({id,lesson:'construct',type:'regex',prompt,answer,explanation,hint:'Zerlege die Sprache in einen freien Anfang, Pflichtzeichen und einen erlaubten Rest.'});
export const questions=[
 q('m1','motivation','„Sortiere die Liste [7,2,5].“ Was ist [7,2,5]?',['Ein Algorithmus','Eine konkrete Instanz','Die Laufzeitklasse'],1,'Das allgemeine Problem ist Sortieren. Diese bestimmte Liste ist eine Eingabeinstanz.'),
 q('m2','motivation','Ein Code hat das vorgeschriebene Format. Was folgt daraus?',['Er ist tatsächlich vergeben.','Seine Syntax ist gültig.','Seine Bedeutung ist korrekt.'],1,'Eine Formatprüfung entscheidet den syntaktischen Aufbau, nicht die tatsächliche Zuordnung.'),
 q('m3','motivation','Welche Frage betrifft Komplexität?',['Wie wächst die Zahl der Rechenschritte mit der Eingabe?','Was bedeutet das Symbol ε?','Welchen Namen hat die Startvariable?'],0,'Komplexität misst Ressourcenverbrauch abhängig von der Eingabegröße.'),
 n('c1','complexity','T(n) = 4n + 2. Wie viele Schritte braucht das Verfahren bei n = 100?',402,'4 · 100 + 2 = 402.'),
 q('c2','complexity','Die Eingabe wächst von n auf 10n. Wie wächst die exakte Schrittzahl n²?',['Um Faktor 10','Um Faktor 20','Um Faktor 100'],2,'(10n)² = 100n². Das gilt für die hier exakt vorgegebene Funktion.'),
 n('c3','complexity','Die Binärdarstellung einer Zahl lautet 1000. Wie viele Bits hat diese Eingabe?',4,'Eingabelänge 4, Zahlenwert 8. Diese Größen nicht verwechseln.'),
 q('c4','complexity','Ein fester DEA liest ein Wort der Länge n. Welche Aussage passt?',['O(n) Übergänge und konstanter zusätzlicher Zustandsspeicher','Exponentiell viele Zustände pro Eingabe','O(1) Übergänge für jedes Wort'],0,'Ein Übergang pro Zeichen; gespeichert wird nur ein Zustand aus der festen endlichen Zustandsmenge.'),
 q('no1','notation','L = {0,10}. Welche Aussage ist richtig?',['{10} ∈ L','10 ⊆ L','{10} ⊆ L'],2,'Das Wort 10 ist Element von L. Die Menge {10} ist eine Teilmenge von L.'),
 n('no2','notation','Wie viele Elemente hat die Menge {0,0,1}?',2,'Doppelte Einträge ändern eine Menge nicht. Die Elemente sind 0 und 1.'),
 q('no3','notation','Was musst du für „P genau dann, wenn Q“ zeigen?',['Nur P ⇒ Q','Beide Richtungen P ⇒ Q und Q ⇒ P','Nur ein Beispiel'],1,'Eine Äquivalenz verlangt beide Implikationen.'),
 s('a1','alphabet','Gib alle Wörter aus {0,1}² an.',['00','01','10','11'],'Für jede der zwei Stellen gibt es zwei Möglichkeiten: 00, 01, 10, 11.'),
 n('a2','alphabet','Wie viele Wörter der Länge 4 gibt es über {a,b}?',16,'Zwei Möglichkeiten an vier Stellen: 2⁴ = 16.'),
 q('a3','alphabet','Σ = {Menschen, Leben, Tanzen, Welt}, jeder Eintrag ein Token. Welche Länge hat „Menschen · Tanzen“?',['2','14','Unendlich'],0,'Hier zählen Tokens, nicht die gedruckten Buchstaben.'),
 q('a4','alphabet','Was enthält P({0,1})?',['Alle endlichen Binärwörter','Alle Teilmengen von {0,1}','Nur Wörter der Länge 2'],1,'P({0,1}) = {∅,{0},{1},{0,1}}. Das ist nicht Σ*.'),
 n('e1','empty','Wie viele Wörter enthält {ε}?',1,'Genau ein Wort: das leere Wort. Dessen Länge ist 0.'),
 s('e2','empty','K = {a,bb}. Berechne K · {ε}.',['a','bb'],'Anhängen von ε ändert nichts: aε = a und bbε = bb.'),
 s('e3','empty','K = {a,bb}. Berechne K · ∅.',[],'Es gibt kein Wort im zweiten Faktor. Deshalb gibt es kein auswählbares Paar.'),
 q('e4','empty','Welches Objekt hat Länge 0?',['Das Wort 0','Das Wort ε','Das Wort 00'],1,'ε enthält kein Symbol. 0 enthält ein Symbol und 00 zwei.'),
 q('la1','languages','L = {0,10,110}. Gehört 010 zu L?',['Ja, weil es nur 0 und 1 enthält','Nein, es steht nicht in der aufgezählten Menge','Ja, weil es Länge 3 hat'],1,'Ein gültiges Wort über dem Alphabet muss nicht Element einer bestimmten Sprache sein.'),
 q('la2','languages','Welches Wort hat gleich viele 0 und 1, liegt aber nicht in {0ⁿ1ⁿ : n ≥ 0}?',['0011','ε','10'],2,'10 hat gleiche Anzahlen, aber die falsche Blockreihenfolge.'),
 q('la3','languages','L = {uav : u ∈ {a,b}*, v ∈ {a,b}}. Welche Beschreibung stimmt?',['Das letzte Zeichen ist a.','Das vorletzte Zeichen ist a.','Es gibt genau ein a.'],1,'Nach dem verpflichtenden a folgt genau ein Zeichen v.'),
 s('s1','sets','A = {ε,0,01}, B = {0,1}. Berechne A ∩ B.',['0'],'Nur 0 liegt in beiden Mengen.'),
 s('s2','sets','A = {ε,0,01}, B = {0,1}. Berechne A ∪ B.',['','0','01','1'],'Alle Wörter aus mindestens einer Menge: ε, 0, 01, 1.'),
 s('s3','sets','A = {ε,0,01}, B = {0,1}. Berechne A ∖ B.',['','01'],'Entferne aus A alle Wörter, die auch in B liegen. Das ist hier nur 0.'),
 q('s4','sets','L enthält alle Binärwörter mit letzter 1. Was ist Lᶜ bezüglich {0,1}*?',['Nur Wörter mit letzter 0','Wörter mit letzter 0 und ε','Alle Wörter mit mindestens einer 0'],1,'ε endet nicht auf 1 und gehört deshalb ebenfalls ins Komplement.'),
 s('co1','concat','A = {ε,0}, B = {1,01}. Berechne A · B.',['1','01','001'],'ε1 = 1, ε01 = 01, 01 = 01, 001 = 001. 01 entsteht doppelt.'),
 s('co2','concat','A = {a,bb}, B = {a}. Berechne B · A.',['aa','abb'],'Erst ein Wort aus B, dann aus A: a·a und a·bb. Die Reihenfolge ist wichtig.'),
 q('co3','concat','Welche Aussage gilt immer für endliche A und B?',['|A·B| = |A|·|B|','|A·B| ≤ |A|·|B|','|A·B| > |A|·|B|'],1,'Jedes Paar erzeugt ein Wort, aber verschiedene Paare können dasselbe Wort erzeugen.'),
 s('cl1','closure','Berechne ∅*.',[''],'Null Wiederholungen liefern ε. Mehr als null Faktoren aus ∅ sind unmöglich.'),
 s('cl2','closure','L = {a,bb}. Berechne L².',['aa','abb','bba','bbbb'],'Wähle unabhängig je ein Wort pro Faktor: a·a, a·bb, bb·a, bb·bb.'),
 q('cl3','closure','Wann liegt ε in L⁺?',['Nie','Immer','Genau dann, wenn ε schon in L liegt'],2,'Eine Verkettung hat nur dann Länge 0, wenn alle Faktoren leer sind. Ein vorhandenes ε genügt.'),
 s('qu1','quotient','A = {00,01,001}, B = {ε,0,1}. Berechne A / B.',['0','00','01','001'],'ε lässt die Wörter stehen; 0 oder 1 als Suffix liefern zusätzlich 0 und 00.'),
 s('qu2','quotient','A = {ab,abb,b}, B = {ε,b}. Berechne A / B.',['','a','ab','abb','b'],'ε lässt alle Wörter stehen. b als Suffix liefert a, ab und ε.'),
 s('qu3','quotient','A = {0}, B = {1}. Berechne A / B.',[],'Kein Wort w erfüllt w1 = 0. Beide Ausgangssprachen sind nichtleer, der Quotient ist leer.'),
 q('re1','regex','Welches Wort gehört zu 01*, aber nicht zu (01)*?',['01','ε','011'],2,'01* erlaubt mehrere 1en nach einer 0. (01)* verlangt vollständige 01-Blöcke.'),
 q('re2','regex','Gehört 01 zu (0 ∪ 1)*0 ∪ 1?',['Ja, der Stern erlaubt alles.','Nein, es endet weder auf 0 noch ist es das einzelne Wort 1.'],1,'Die abschließende Vereinigung mit 1 bindet schwächer als die Verkettung.'),
 q('re3','regex','Welche Wörter enthält 0*1 ∪ ε?',['Nur Wörter mit mindestens einer 0','ε sowie beliebig viele 0 gefolgt von genau einer 1','Alle Wörter mit mindestens einer 1'],1,'Null 0 sind erlaubt: Auch 1 gehört dazu. Nach der verpflichtenden 1 kommt nichts mehr.'),
 r('rc1','Schreibe einen RegEx für alle Binärwörter, die auf 01 enden.','(0|1)*01','Ein beliebiger Binäranfang, danach das verpflichtende Ende 01.'),
 r('rc2','Schreibe einen RegEx für Binärwörter mit genau zwei Einsen.','0*10*10*','Die beiden 1 sind verpflichtend. Vor, zwischen und nach ihnen stehen nur Nullen.'),
 r('rc3','Schreibe einen RegEx für Binärwörter ohne eine einzige 1.','0*','Nur Nullen, auch null Stück. ε gehört daher dazu.'),
 r('rc4','Schreibe einen RegEx für alle Binärwörter mit genau Länge 3.','(0|1)(0|1)(0|1)','Drei unabhängige Stellen, an jeder 0 oder 1.'),
 q('d1','dfa','Ein DEA erreicht nach dem ersten Zeichen einen Endzustand. Ist das Wort damit akzeptiert?',['Ja, die Verarbeitung endet sofort.','Nur wenn auch nach dem gesamten Wort ein Endzustand erreicht ist.'],1,'Endzustände sind akzeptierend, aber keine Stoppanweisung.'),
 q('d2','dfa','Wann akzeptiert ein DEA ε?',['Wenn es irgendwo einen Endzustand gibt','Wenn der Startzustand akzeptierend ist','Nie'],1,'ε verursacht keinen Übergang; der Start ist zugleich der letzte Zustand.'),
 q('d3','dfa','A: bei 0 → B, bei 1 → A. B: bei 0 → B, bei 1 → A. Start A, nur B akzeptiert. Was passiert bei 101?',['Ende B, akzeptiert','Ende A, abgelehnt','Ende A, akzeptiert'],1,'A → A → B → A. Dieser Automat akzeptiert Wörter mit letzter 0.'),
 q('p1','parity','Ein Paritätsautomat startet in G. Welche Eingabe wechselt den Zustand?',['0','1','Beide'],1,'Nur eine weitere 1 ändert die Parität der Anzahl Einsen.'),
 q('p2','parity','Warum wird ε bei „gerade Anzahl Einsen“ akzeptiert?',['Weil jeder DEA ε akzeptiert','Weil null Einsen eine gerade Anzahl ist','Weil ε eine 0 enthält'],1,'Der akzeptierende Startzustand steht für null gelesene Einsen.'),
 q('p3','parity','Warum reichen zwei Zustände für beliebig viele Einsen?',['Sie speichern jede genaue Anzahl.','Sie speichern nur gerade oder ungerade.','Die Wortlänge ist auf zwei begrenzt.'],1,'Für diese Bedingung ist nur der Rest modulo 2 nötig, nicht die genaue Anzahl.'),
 q('al1','alternate','Kein 00 und kein 11 erlaubt. Welches Wort muss abgelehnt werden?',['ε','0101','011'],2,'011 enthält zwei gleiche benachbarte Einsen.'),
 q('al2','alternate','Wozu dient X nach einem gefundenen 00 oder 11?',['Der Rest kann den Fehler rückgängig machen.','Es merkt den bleibenden Verstoß und bleibt auf beiden Zeichen in X.','Es startet den Automaten neu.'],1,'Ein bereits vorhandenes verbotenes Teilwort verschwindet durch Anhängen nicht.'),
 q('al3','alternate','Ein Automat erkennt {do,double,catch,case}. Darf ein akzeptierender Zustand für „do“ einen sinnvollen Übergang auf u haben?',['Ja, denn „double“ beginnt mit „do“.','Nein, ein Endzustand hat keine Übergänge.'],0,'Akzeptanz wird erst am Eingabeende geprüft. „do“ ist gleichzeitig Wort und Präfix eines längeren Wortes.'),
 s('cp1','complement','Q = {q0,q1,q2,q3,err}, F = {q0,q1}. Welche Endzustände hat das Komplement?',['q2','q3','err'],'Alle Zustände aus Q ohne die bisherigen Endzustände. Auch err wird akzeptierend.'),
 q('cp2','complement','Was ist vor dem Vertauschen der Endzustände nötig?',['Den vollständigen DEA sicherstellen','Alle Schleifen löschen','Den Startzustand wechseln'],0,'Ohne vollständige Übergänge können Wörter verschwinden, statt im Komplement akzeptiert zu werden.'),
 q('cp3','complement','Ein vollständiger DEA akzeptiert ε. Was tut sein Komplement?',['Akzeptiert ε ebenfalls','Lehnt ε ab','Hält bei ε nicht'],1,'Der Startzustand wechselt von akzeptierend zu nicht akzeptierend.'),
 q('g1','grammar','G: S → 0S | 1. Welche Folge ist ein fertiges Wort?',['00S','S','001'],2,'Fertige Wörter enthalten nur Terminalzeichen. S ist eine Variable.'),
 q('g2','grammar','Welche Sprache erzeugt S → 0S | 1?',['{0ⁿ1 : n ≥ 0}','{0ⁿ1ⁿ : n ≥ 0}','Alle Binärwörter'],0,'Jede 0S-Regel fügt eine 0 hinzu, S → 1 beendet mit genau einer 1.'),
 q('g3','grammar','Was gilt für Terminalalphabet Σ und Variablenmenge V?',['Σ = V','Σ ∩ V = ∅','Σ muss unendlich sein'],1,'Terminalzeichen und Variablen sind disjunkte Symbolmengen.'),
 q('h1','hierarchy','Welches Modell gehört zu kontextfreien Sprachen?',['Nur endliche Automaten','Nichtdeterministischer Kellerautomat','Ausschließlich ein einzelner Zähler bis 10'],1,'Der zusätzliche Stack ermöglicht unbeschränkte Verschachtelungen.'),
 q('h2','hierarchy','Eine Sprache ist nicht regulär. Was folgt?',['Sie ist zwingend kontextfrei.','Sie kann kontextfrei sein, muss es aber nicht.','Sie ist zwingend unentscheidbar.'],1,'Zum Beispiel ist {aⁿbⁿcⁿ} nicht kontextfrei, aber kontextsensitiv.'),
 q('h3','hierarchy','Was gilt für eine reguläre Sprache?',['Sie ist auch kontextfrei.','Sie ist nie kontextfrei.','Sie ist unentscheidbar.'],0,'Reguläre Sprachen bilden eine echte Teilklasse der kontextfreien Sprachen.'),
 q('t1','transfer','Warum ist jede endliche Sprache regulär?',['Weil man die endlich vielen Wörter durch ∪ verbinden kann','Weil jede Sprache endlich ist','Weil jede Sprache von einem DEA erkannt wird'],0,'Jedes endliche Wort ist eine Verkettung von Grundzeichen; eine endliche Vereinigung bleibt regulär.'),
 q('t2','transfer','Ein Automat akzeptiert alle Binärwörter. Ist er damit ein Prüfer, der genau die Primzahlkodierungen akzeptiert?',['Ja','Nein, er akzeptiert auch Nichtprimzahlen'],1,'Die stärkere Forderung „genau“ verbietet falsche positive Ergebnisse.'),
 q('t3','transfer','Welche Gleichung hilft, die Abgeschlossenheit unter Schnitt zu zeigen?',['A ∩ B = (Aᶜ ∪ Bᶜ)ᶜ','A ∩ B = A · B','A ∩ B = A ∪ B'],0,'De Morgan verknüpft Schnitt mit Komplement und Vereinigung, unter denen reguläre Sprachen abgeschlossen sind.')
];
export const checkQuestions = [
 q('w1','alphabet','Welches Wort liegt über dem Alphabet {0,1}?',['012','010','2'],1,'010 besteht ausschließlich aus erlaubten Symbolen. 012 enthält eine unerlaubte 2.'),
 q('w2','empty','Wie unterscheiden sich ∅ und {ε}?',['Beide enthalten null Wörter.','∅ enthält null Wörter; {ε} enthält ein Wort.','Beide enthalten ein Wort.'],1,'Die Länge des enthaltenen Wortes und die Anzahl der Wörter sind verschiedene Größen.'),
 s('w3','alphabet','Schreibe alle Wörter der Länge 2 über {a,b} auf.',['aa','ab','ba','bb'],'Zwei Möglichkeiten pro Stelle: 2² = 4 Wörter.'),
 q('w4','sets','A = {0}, B = {1}. Was ist A ∪ B, was A · B?',['Beides {01}','{0,1} und {01}','{01} und {0,1}'],1,'Vereinigung wählt die vorhandenen Wörter; Verkettung hängt 0 und 1 aneinander.'),
 n('w5','concat','A = B = {ε,0}. Wie viele verschiedene Wörter enthält A · B?',3,'Die Wörter sind ε, 0 und 00. Zwei verschiedene Paare erzeugen 0.'),
 q('w6','regex','Welches Wort gehört NICHT zu (0 ∪ 1)*1?',['1','001','ε'],2,'Eine abschließende 1 ist verpflichtend. ε enthält kein Zeichen.'),
 q('w7','regex','Warum gehört 010 nicht zu (01)*?',['Es enthält zu viele Nullen.','Es besteht nicht vollständig aus 01-Blöcken.','Der Stern erlaubt nur einen Block.'],1,'Ein ganzer Block 01 und ein unvollständiger Rest 0 bleiben übrig.'),
 q('w8','dfa','Ein DEA ist nach dem gesamten Wort in q2. Was entscheidet über die Annahme?',['Ob q2 ∈ F','Ob q2 der Start ist','Ob unterwegs F besucht wurde'],0,'Der Endzustand nach vollständiger Eingabe ist maßgeblich.'),
 q('w9','complement','Wie komplementierst du einen vollständigen DEA?',['Start und Endzustände vertauschen','F durch Q ∖ F ersetzen','Alle Pfeile umdrehen'],1,'Alle übrigen Bestandteile bleiben gleich.'),
 q('w10','parity','Welche Information genügt für „gerade Anzahl Einsen“?',['Die genaue Wortlänge','Die genaue Anzahl Einsen','Nur gerade oder ungerade'],2,'Eine 1 wechselt zwischen den beiden Möglichkeiten; 0 lässt sie unverändert.')
];
export const allQuestions=[...questions,...checkQuestions];
export const questionById=Object.fromEntries(allQuestions.map(q=>[q.id,q]));
export const achievements=[
 {id:'first',title:'Zündung',description:'Die erste Aufgabe richtig lösen.',icon:'spark',rule:s=>Object.values(s.results).some(r=>r.successes?.length)},
 {id:'ten',title:'Im Lernorbit',description:'10 verschiedene Aufgaben richtig lösen.',icon:'orbit',rule:s=>Object.values(s.results).filter(r=>r.successes?.length).length>=10},
 {id:'lesson',title:'Ein Baustein sitzt',description:'Eine Lektion mit mindestens 80 % abschließen.',icon:'book',rule:s=>Object.keys(s.completed).length>=1},
 {id:'five',title:'Fundamentbauer',description:'Fünf Lektionen abschließen.',icon:'layers',rule:s=>Object.keys(s.completed).length>=5},
 {id:'builder',title:'Automatenarchitekt',description:'Einen eigenen DEA korrekt konstruieren.',icon:'nodes',rule:s=>Object.keys(s.builders).length>=1},
 {id:'repair',title:'Fehlerforscher',description:'Eine zuvor falsche Aufgabe später richtig lösen.',icon:'search',rule:s=>Object.values(s.results).some(r=>r.repaired)},
 {id:'three',title:'Dranbleiber',description:'An drei aufeinanderfolgenden Tagen üben.',icon:'flame',rule:(_s,streak)=>streak>=3},
 {id:'check',title:'Woche 1 gemeistert',description:'8/10 im Wochencheck und beide Pflicht-DEAs ohne Vorlage.',icon:'trophy',rule:s=>s.checks.some(c=>c.score>=8)&&s.builders.ends1&&s.builders.alternate},
 {id:'boss1',title:'Bossbezwinger',description:'Einen Bosskampf mit mindestens einem Leben gewinnen.',icon:'shield',rule:s=>Object.keys(s.bosses||{}).length>=1},
 {id:'bossall',title:'Hüter des Fundaments',description:'Alle fünf Bosse von Woche 1 besiegen.',icon:'flag',rule:s=>units.every(u=>s.bosses?.[u.id])},
 {id:'blitz10',title:'Geistesblitz',description:'In einer Blitzrunde 10 richtige Antworten schaffen.',icon:'spark',rule:s=>(s.blitz||[]).some(b=>b.score>=10)},
 {id:'cards30',title:'Kartenmeister',description:'30 Karteikarten mindestens ins dritte Fach bringen.',icon:'layers',rule:s=>Object.values(s.cards||{}).filter(c=>c.box>=3).length>=30},
 {id:'quests',title:'Missionsheld',description:'An einem Tag alle drei Tagesmissionen erfüllen.',icon:'target',rule:s=>{const per={};for(const k of Object.keys(s.awards))if(k.startsWith('quest:')){const d=k.slice(6,16);per[d]=(per[d]||0)+1;}return Object.values(per).some(n=>n>=3);}},
 {id:'all',title:'Fundament komplett',description:'Alle 19 Lektionen abschließen.',icon:'flag',rule:s=>Object.keys(s.completed).length===lessons.length}
];
