import {questionDfaFeedback} from './dfa-view.js';
import {exams,examById} from './exams.js';
import {examReport,remainingSeconds,hasAnswer,correctAnswer} from './exam-engine.js';
import {topicById} from './curriculum.js';
export function graphView(graph,esc){
 const points=Object.fromEntries(graph.vertices.map((v,i)=>[v,[150+105*Math.cos(i*2*Math.PI/graph.vertices.length-Math.PI/2),135+100*Math.sin(i*2*Math.PI/graph.vertices.length-Math.PI/2)]]));
 return `<figure class="exam-graph"><svg viewBox="0 0 300 270" role="img" aria-label="Ungerichteter Graph; die Kantenliste steht im Aufgabentext.">${graph.edges.map(([a,b])=>`<line x1="${points[a][0]}" y1="${points[a][1]}" x2="${points[b][0]}" y2="${points[b][1]}" class="g-edge" stroke-width="2"/>`).join('')}${graph.vertices.map(v=>`<circle cx="${points[v][0]}" cy="${points[v][1]}" r="19" class="g-node" stroke-width="2"/><text x="${points[v][0]}" y="${points[v][1]+5}" text-anchor="middle" class="g-label" font-size="17">${esc(v)}</text>`).join('')}</svg><figcaption class="help">Maßgeblich ist die Kantenliste im Text.</figcaption></figure>`;
}
const displayValue=(q,v)=>!hasAnswer(v)?'Keine Antwort':q.type==='choice'?q.options[Number(v)]:v;
function promptView(q,{esc}){return `<p class="exam-prompt">${esc(q.prompt)}</p>${q.materials?.graph?graphView(q.materials.graph,esc):''}`;}
export function examRoom(state,{head,esc,icon,time}){
 const drafts=state.examAttempts.filter(a=>a.submittedAt===null),finished=state.examAttempts.filter(a=>a.submittedAt!==null).slice().reverse();
 return `${head('DEIN KLAUSURRAUM','Zeig, was ohne Vorlage bleibt.','Drei Grundlagenchecks, der Wochencheck für Woche 2 und drei vollständige Probeklausuren. Mit Auswertung und einem konkreten nächsten Lernschritt.')}
 <div class="callout"><strong>Erst bearbeiten, dann Lösungen vergleichen.</strong>Antworten werden auf diesem Gerät gespeichert. Du kannst zurückblättern, Aufgaben markieren und nach dem Neuladen fortsetzen. Bei einem Zeitlimit läuft die Uhr auch außerhalb der App weiter. Sie erinnert dich an die Zeit; abgegeben wird bewusst von dir.</div>
 ${drafts.length?`<section class="card" style="margin-top:22px"><h2>Hier kannst du weitermachen</h2>${drafts.map(a=>`<div class="lesson-row"><div><h3>${examById[a.examId].title}</h3><p>${Object.values(a.answers).filter(hasAnswer).length}/${examById[a.examId].questions.length} beantwortet · ${a.limitSeconds?time(remainingSeconds(a))+' verbleibend':'ohne Zeitlimit'}</p></div><a class="btn" href="#exam/${a.id}">Fortsetzen ${icon('arrow')}</a></div>`).join('')}</section>`:''}
 ${['mini','week','full'].map(kind=>`<div class="section-heading"><h2>${kind==='mini'?'Woche 1 · kurze Standortbestimmung':kind==='week'?'Woche 2 · Automaten & Übersetzungen':'Ganzer Stoff · 60 Punkte je Probeklausur'}</h2></div><div class="grid exam-grid">${exams.filter(e=>e.kind===kind).map(e=>{const attempts=finished.filter(a=>a.examId===e.id);return `<article class="card exam-card"><span class="pill ${kind==='mini'?'gray':'purple'}">${e.points} PUNKTE · ${e.questions.length} AUFGABEN</span><h2>${e.title}</h2><h3>${e.subtitle}</h3><p class="small muted">${e.description}</p><label class="field">Dein Zeitrahmen<select id="duration-${e.id}">${[...new Set([0,e.suggestedMinutes,90,120])].map(n=>`<option value="${n}">${n?n+' Minuten':'Ohne Zeitlimit'}</option>`).join('')}</select></label><button class="btn ${kind==='mini'?'secondary':''}" data-action="exam-start" data-id="${e.id}">${drafts.some(a=>a.examId===e.id)?'Fortsetzen':attempts.length?'Bekannte Variante wiederholen':'Klausur starten'} ${icon('arrow')}</button><p class="help">${attempts.length?`${attempts.length} frühere Durchläufe. Wiederholung trainiert Routine; die Variante ist dann kein neuer Leistungsnachweis.`:'Noch nicht bearbeitet. Musterlösungen erscheinen erst nach der Abgabe.'}</p></article>`;}).join('')}</div>`).join('')}
 <section class="card" style="margin-top:24px"><h2>Deine bisherigen Klausuren</h2>${finished.length?`<div class="table-scroll"><table><thead><tr><th>Klausur</th><th>Datum</th><th>Automatisch</th><th>Selbst bewertet</th><th>Auswertung</th></tr></thead><tbody>${finished.map(a=>{const r=examReport(a);return `<tr><td>${examById[a.examId].title}${a.knownVariant?' · wiederholt':''}</td><td>${new Date(a.submittedAt).toLocaleDateString('de-DE')}</td><td>${r.autoPoints}/${r.autoMax}</td><td>${r.selfPoints}/${r.selfMax}${r.pendingPoints?' · offen':''}</td><td><a href="#exam/${a.id}">Ansehen →</a></td></tr>`;}).join('')}</tbody></table></div>`:'<p class="muted small">Noch keine Klausur abgegeben. Deine Ergebnisse werden hier gesammelt.</p>'}</section>
 <p class="help" style="margin-top:20px">Die Original-Altklausur bleibt als zusätzliche unbekannte Generalprobe sinnvoll. Dies sind eigene Übungsaufgaben, keine Vorhersage der echten Klausur. Die Punktverteilung der großen Varianten ist 8 / 10 / 7 / 15 / 10 / 10. Selbstbewertungen zählen nicht als automatisch bestätigte Kompetenz.</p>`;
}
export function attemptView(a,helpers){
 const {head,esc,icon,time}=helpers,exam=examById[a.examId];
 if(a.submittedAt!==null)return resultView(a,helpers);
 const q=exam.questions[a.index],value=a.answers[q.id]||'',done=Object.values(a.answers).filter(hasAnswer).length,remaining=remainingSeconds(a);
 return `<a href="#exams" class="back-link no-print">${icon('back')} Speichern & zum Klausurraum</a>${head(`${exam.kind==='mini'?'WOCHE 1':'ALLE KAPITEL'} · ${exam.points} PUNKTE`,exam.title,exam.subtitle)}
 <div class="exam-toolbar no-print"><span class="pill purple">${done}/${exam.questions.length} beantwortet</span><span class="pill gray" id="exam-timer">${remaining===null?'Ohne Zeitlimit':remaining===0?'Trainingszeit abgelaufen':time(remaining)+' verbleibend'}</span><button class="btn ghost" data-action="exam-print">${icon('download')} Drucken / PDF</button><span class="help" id="exam-save-status" role="status"></span></div>
 <p class="help no-print">${a.limitSeconds?'Die Uhr läuft auch bei geschlossener App weiter. Nach Ablauf kannst du bewusst abgeben oder zu Übungszwecken weiterarbeiten.':'Arbeite ohne Zeitdruck und begründe deine Lösungen.'} Alle Eingaben bleiben lokal gespeichert. Offene Aufgaben: Kurzfassung eintragen oder „auf Papier gelöst“, wenn du deinen ausführlichen Lösungsweg dort notierst.</p>
 <div class="exam-layout no-print"><aside class="card exam-navigation"><h2>Aufgaben</h2><nav aria-label="Aufgabennavigation">${exam.questions.map((item,i)=>`<button data-action="exam-jump" data-index="${i}" class="exam-step ${i===a.index?'current':''} ${hasAnswer(a.answers[item.id])?'answered':''}" ${i===a.index?'aria-current="step"':''} aria-label="Aufgabe ${i+1}, ${item.section}${hasAnswer(a.answers[item.id])?', beantwortet':''}${a.flags.includes(item.id)?', markiert':''}">${i+1}${a.flags.includes(item.id)?' ⚑':''}</button>`).join('')}</nav><p class="help">Grün = Eingabe vorhanden, noch keine Bewertung. ⚑ = später prüfen.</p><button class="btn secondary" data-action="exam-submit-review">Zur Abgabe ${icon('arrow')}</button></aside>
 <section class="card exam-question"><div class="eyebrow">AUFGABE ${a.index+1} · ${q.section} · ${q.points} ${q.points===1?'PUNKT':'PUNKTE'}</div><h2>${q.type==='open'?'Begründe deinen Lösungsweg.':'Dein Ergebnis zählt.'}</h2>${promptView(q,helpers)}
 ${q.type==='choice'?`<fieldset class="exam-choices"><legend class="sr-only">Deine Antwort</legend>${q.options.map((o,i)=>`<label class="answer ${value===String(i)?'selected':''}"><input type="radio" name="exam-choice" data-exam-answer="${q.id}" value="${i}" ${value===String(i)?'checked':''}>${esc(o)}</label>`).join('')}</fieldset>`:`<label class="field"><span>${q.type==='open'?'Deine Begründung / dein Lösungsweg':q.type==='set'?'Menge eingeben, z. B. {S,A} oder ∅':q.type==='regex'?'Regulärer Ausdruck über {0,1}':'Deine Antwort'}</span>${q.type==='open'?`<textarea rows="9" data-exam-answer="${q.id}" id="exam-input" maxlength="4000" placeholder="Schreibe deine Begründung oder notiere, was du auf Papier gelöst hast.">${esc(value)}</textarea>`:`<input id="exam-input" data-exam-answer="${q.id}" value="${esc(value)}" maxlength="${q.type==='regex'?120:1000}" ${q.type==='number'?'inputmode="numeric"':''} spellcheck="false" autocomplete="off">`}</label>${['regex','set','open'].includes(q.type)?`<div class="symbol-keyboard">${['ε','∅','∪','→','⊆','{','}','*'].map(symbol=>`<button type="button" data-action="symbol" data-target="exam-input" data-symbol="${esc(symbol)}" aria-label="${esc(symbol)} einfügen">${symbol}</button>`).join('')}</div>`:''}`}
 <p class="help">${q.type==='open'?'Nach der Abgabe vergleichst du deinen Lösungsweg mit Musterlösung und Punkte-Raster. Offene Texte werden nicht automatisch benotet.':'Diese Teilaufgabe wird nach der Abgabe automatisch geprüft. Formatfehler zählen dann als falsch; leere Mengen bitte ausdrücklich mit ∅ eingeben.'}</p>
 <div class="exam-controls"><button class="btn ghost" data-action="exam-flag" aria-pressed="${a.flags.includes(q.id)}">${a.flags.includes(q.id)?'⚑ Markierung entfernen':'⚑ Für später markieren'}</button><div class="inline-actions"><button class="btn secondary" data-action="exam-jump" data-index="${a.index-1}" ${a.index===0?'disabled':''}>Zurück</button>${a.index+1<exam.questions.length?`<button class="btn" data-action="exam-jump" data-index="${a.index+1}">Weiter ${icon('arrow')}</button>`:'<button class="btn" data-action="exam-submit-review">Zur Abgabe →</button>'}</div></div><div id="exam-submit-panel" role="status"></div></section></div>
 <div class="exam-print-only">${exam.questions.map((item,i)=>`<section class="print-question"><h2>${i+1}. ${item.section} · ${item.points} Punkte</h2>${promptView(item,helpers)}${item.options?`<ol type="A">${item.options.map(o=>`<li>${esc(o)}</li>`).join('')}</ol>`:''}<p class="exam-answer">${esc(displayValue(item,a.answers[item.id]))}</p><div class="print-space"></div></section>`).join('')}</div>`;
}
function resultView(a,helpers){
 const {head,esc,icon,time}=helpers,exam=examById[a.examId],report=examReport(a),seconds=Math.max(0,Math.round((a.submittedAt-a.startedAt)/1000)),over=a.limitSeconds&&seconds>a.limitSeconds;
 return `<a href="#exams" class="back-link no-print">${icon('back')} Alle Klausuren</a>${head(`${exam.title.toUpperCase()} · AUSWERTUNG`,report.complete?'Du weißt, woran du weiterarbeiten kannst.':'Deine Begründungen warten auf den Vergleich.',`${time(seconds)} seit Start bis Abgabe${over?' · Trainingszeit überschritten':''}${a.knownVariant?' · bekannte Variante wiederholt':''}. Keine offizielle Note.`)}
 <div class="stats-grid exam-scores"><section class="card stat-big"><strong>${report.autoPoints}/${report.autoMax}</strong><p>Automatisch geprüft</p></section><section class="card stat-big"><strong>${report.selfPoints}/${report.selfMax}</strong><p>Selbst bewertet</p></section><section class="card stat-big"><strong>${report.pendingPoints}</strong><p>Punkte noch zu beurteilen</p></section><section class="card stat-big"><strong>${report.total}/${report.max}</strong><p>${report.complete?'Gesamt inklusive Selbstbewertung':'Vorläufig inklusive Selbstbewertung'}</p></section></div>
 <section class="card"><h2>Dein nächster Lernschritt</h2><p class="small muted">Arbeite zuerst an einem schwachen Teilgebiet. Lies die Erklärung, übe eine neue Variante und komme an einem anderen Tag darauf zurück.</p><div class="table-scroll"><table><thead><tr><th>Teilgebiet</th><th>Stand</th><th>Weiterlernen</th></tr></thead><tbody>${report.sections.map(s=>`<tr><td>${s.title}</td><td>${s.points}/${s.max}${s.pending?' · Selbstbewertung offen':''}</td><td>${s.topics.length?s.topics.map(t=>`<a class="topic-link" href="#practice/${t}">${topicById[t].title} →</a>`).join(''):s.pending?'Erst unten selbst bewerten':'✓ Trainingsziel erreicht'}</td></tr>`).join('')}</tbody></table></div></section>
 <div class="inline-actions no-print" style="margin:22px 0"><a href="#practice" class="btn">Neue Varianten üben ${icon('arrow')}</a><button class="btn secondary" data-action="exam-print">Auswertung drucken / PDF</button></div>
 ${exam.questions.map((q,i)=>{const r=report.items[i];return `<section class="card exam-review"><div class="eyebrow">${i+1} · ${q.section} · ${r.points}/${q.points} PUNKTE ${r.pending?'· NOCH OFFEN':r.automatic?'· AUTOMATISCH':'· SELBST BEWERTET'}</div>${promptView(q,helpers)}<h3>Deine abgegebene Antwort</h3><p class="exam-answer">${esc(displayValue(q,a.answers[q.id]))}</p>${questionDfaFeedback({...q,lesson:q.topic},esc,`exam-${a.id}`)}<details ${q.type==='open'&&r.pending?'open':''}><summary>Musterlösung & ${q.type==='open'?'Bewertungsraster':'Erklärung'} ansehen</summary><div class="feedback ${r.automatic&&r.points<q.points?'error':'info'}">${q.type==='open'?'':`<strong>${esc(correctAnswer(q))}</strong>`}<p class="exam-answer">${esc(q.solution)}</p>${r.error?`<p>${esc(r.error)}</p>`:''}</div>${q.type==='open'?hasAnswer(a.answers[q.id])?`<p class="help">Vergleiche ehrlich mit deinem abgegebenen Text oder deinem Papier. Gleichwertige korrekte Wege zählen. Wähle ausdrücklich 0, wenn ein Kriterium fehlt.</p><div class="rubric">${q.rubric.map((row,j)=>`<label class="rubric-row"><span>${esc(row.text)}</span><select data-exam-rating="${q.id}" data-criterion="${j}" aria-label="Aufgabe ${i+1}, Kriterium ${j+1}: Punkte"><option value="">Noch offen</option>${Array.from({length:row.points+1},(_,n)=>`<option value="${n}" ${a.ratings[q.id]?.[j]===n?'selected':''}>${n} / ${row.points}</option>`).join('')}</select></label>`).join('')}</div>`:'<p class="help">Keine Antwort abgegeben: 0 Punkte. Für einen neuen Versuch starte die Klausur erneut.</p>':''}</details></section>`;}).join('')}`;
}
