// Independently authored examples. No quiz completion or XP is granted for reading.
const guide = (goal,recipe,prompt,steps,check,answer,exam,table) =>
  ({goal,recipe,worked:{prompt,steps,table},check,answer,exam});
export const lessonGuides = {
 motivation: guide('Eine Alltagssituation in Eingabe, Entscheidungsfrage und Verfahren übersetzen.',
  ['Benenne die gesamte Eingabemenge.','Formuliere eine eindeutige Ja/Nein-Bedingung.','Trenne die korrekte Antwort von den Kosten ihrer Berechnung.'],
  'Ein System erlaubt Kennungen aus genau drei Binärzeichen. Ist 010 gültig?',
  ['Das Problem ist die Prüfung beliebiger Kennungen; 010 ist eine konkrete Instanz.','Das Alphabet ist {0,1}; die gültige Sprache ist {w ∈ {0,1}* : |w|=3}.','Ein Verfahren zählt die Zeichen und prüft jedes Zeichen. 010 wird akzeptiert, 01 und 01a werden abgelehnt.','Ob die Kennung vergeben ist, lässt sich aus dieser Syntaxregel nicht ableiten.'],
  'Warum löst eine einzige akzeptierte Kennung noch nicht das allgemeine Problem?',
  'Ein allgemeiner Algorithmus muss alle zulässigen Eingaben korrekt behandeln. Ein Beispiel ist nur ein Testfall.', 'method-basics'),
 complexity: guide('Eingabegröße, Laufzeit und Speicherbedarf sauber auseinanderhalten.',
  ['Lege fest, was n zählt.','Zähle die Durchläufe statt nur die Zahl der Schleifen.','Gib eine asymptotische Schranke und das betrachtete Ressourcenmaß an.'],
  'Für jedes i von 1 bis n läuft j von 1 bis i. Wie oft wird der Schleifenrumpf ausgeführt?',
  ['Bei n=4 ergeben sich 1+2+3+4=10 Durchläufe.','Allgemein ist die Summe n(n+1)/2 = (n²+n)/2.','Das Wachstum ist quadratisch: Θ(n²), damit insbesondere O(n²).','Die Laufvariablen brauchen nicht n² Speicherzellen. Laufzeit und Speicher sind getrennte Größen.'],
  'Eine Binärzahl hat n Bits. Ist eine Schleife bis zu ihrem Zahlenwert polynomial in n?',
  'Nicht im Allgemeinen: Der Zahlenwert kann fast 2ⁿ betragen. Eine solche Schleife kann exponentiell in der Eingabelänge sein.', 'method-basics',
  {headers:['n','Durchläufe'],rows:[['1','1'],['2','3'],['3','6'],['4','10']]}),
 notation: guide('Eine Mengenbedingung in verständliche Aussagen und vollständige Beispiele übersetzen.',
  ['Unterscheide Wörter, Mengen und Zahlen.','Lies ∀ als „für alle“ und ∃ als „mindestens eines“.','Prüfe eine allgemeine Behauptung mit Randfällen.'],
  'L={w ∈ {a,b}* : |w|=2 und w beginnt mit a}.',
  ['Zuerst alle Wörter der Länge 2: aa, ab, ba, bb.','Die Anfangsbedingung lässt aa und ab übrig: L={aa,ab}.','ab ∈ L ist eine Aussage über ein Wort. {ab} ⊆ L ist eine Aussage über eine Menge.','ε ∉ L, weil seine Länge 0 statt 2 ist.'],
  'Was widerlegt „Alle Wörter in {a,b}* beginnen mit a“?',
  'Ein Gegenbeispiel genügt, etwa b. Auch ε beginnt nicht mit a.', 'method-basics'),
 alphabet: guide('Wörter systematisch aufzählen und ihre Anzahl ohne Auslassungen bestimmen.',
  ['Bestimme die Zahl der verfügbaren Zeichen k.','Bei genau n Stellen gibt es kⁿ Wörter.','Bei höchstens n Stellen addiere die Anzahlen der einzelnen Längen einschließlich 0.'],
  'Wie viele Wörter über {a,b} haben höchstens Länge 2?',
  ['Länge 0 liefert genau ε.','Länge 1 liefert a und b.','Länge 2 liefert aa, ab, ba, bb.','Insgesamt: 1+2+4=7. Kombinationen ohne Reihenfolge wären falsch, denn ab und ba sind verschieden.'],
  'Warum zählt der Binomialkoeffizient „2 aus 2“ hier nicht die Wörter der Länge 2?',
  'Wörter erlauben Wiederholung und unterscheiden Reihenfolgen. Jede der zwei Stellen hat unabhängig zwei Möglichkeiten: 2²=4.', 'method-basics'),
 empty: guide('ε, ∅ und {ε} in Rechenaufgaben zuverlässig unterscheiden.',
  ['Frage zuerst: Wort oder Sprache?','Zähle bei Mengen die Elemente, bei Wörtern die Zeichen.','Teste die Operation anhand ihrer Definition.'],
  'L={a,bb}. Vergleiche L·∅, L·{ε} und ∅*.',
  ['Für L·∅ kann kein rechtes Wort gewählt werden: Das Ergebnis ist ∅.','Für L·{ε} wird an a oder bb nichts angehängt: Das Ergebnis ist L.','∅* erlaubt null Faktoren. Diese Verkettung ist ε, also ∅*={ε}.','Damit gilt |∅|=0, |{ε}|=1 und |ε|=0.'],
  'Ist {∅} eine Sprache über {a,b}?',
  'Nein. Ihr Element ist eine Menge, kein Wort über {a,b}. {ε} ist dagegen eine solche Sprache.', 'method-basics'),
 languages: guide('Die Zugehörigkeit eines Wortes aus einer Sprachdefinition begründen.',
  ['Übersetze jede Bedingung einzeln.','Prüfe das ganze Wort, nicht nur einen Ausschnitt.','Nenne für eine Ablehnung die konkret verletzte Bedingung.'],
  'L={aⁱbʲ : i≥1 und j≥2}. Gehören abb, aabbb, ab und baba dazu?',
  ['abb besitzt einen a-Block der Länge 1 und einen b-Block der Länge 2: ja.','aabbb hat i=2, j=3: ebenfalls ja.','ab hat nur ein b: nein.','baba hat weder die verlangte Blockreihenfolge noch passende zusammenhängende Blöcke: nein.'],
  'Fordert aⁱbʲ gleiche Anzahlen von a und b?',
  'Nein. i und j sind unabhängig, solange keine zusätzliche Beziehung angegeben ist. Bei aⁿbⁿ ist derselbe Exponent dagegen eine Gleichheitsbedingung.', 'method-basics'),
 sets: guide('Mengenoperationen auf Sprachen mit einer vollständigen Falltabelle lösen.',
  ['Liste jedes vorkommende Wort einmal auf.','Prüfe für jedes Wort die Zugehörigkeit links und rechts.','Beim Komplement zuerst das gemeinsame Alphabet festlegen.'],
  'A={ε,a,ab}, B={a,b}. Berechne A∪B, A∩B und A∖B.',
  ['Die Vereinigung enthält alle Kandidaten: {ε,a,ab,b}.','Nur a kommt in beiden Sprachen vor: A∩B={a}.','Aus A werden die Wörter aus B gestrichen: A∖B={ε,ab}.','Für Aᶜ über {a,b}* gehören zusätzlich beliebig lange Wörter wie aaa dazu. Eine endliche Kandidatenliste reicht dafür nicht.'],
  'Ist A∖B immer gleich B∖A?',
  'Nein. Hier ist A∖B={ε,ab}, aber B∖A={b}. Die Reihenfolge der Differenz zählt.', 'method-languages',
  {headers:['Wort','in A','in B','in A∩B'],rows:[['ε','ja','nein','nein'],['a','ja','ja','ja'],['ab','ja','nein','nein'],['b','nein','ja','nein']]}),
 concat: guide('Jedes Wortpaar prüfen und doppelte Ergebnisse als Mengenelemente zusammenfassen.',
  ['Setze Wörter aus A in Zeilen, Wörter aus B in Spalten.','Trage in jede Zelle zuerst das linke, dann das rechte Wort ein.','Lies die Ergebnismenge ab und entferne Duplikate.'],
  'A={ε,a}, B={b,ab}. Berechne A·B und seine Größe.',
  ['Die Tabelle hat 2·2=4 Zellen, also vier Paare.','ε·b=b, ε·ab=ab, a·b=ab und a·ab=aab.','ab entsteht auf zwei Wegen, zählt in einer Menge aber nur einmal.','A·B={b,ab,aab} hat daher nur drei Elemente.'],
  'Wann darfst du |A·B|=|A|·|B| verwenden?',
  'Wenn verschiedene Paare stets verschiedene Wörter erzeugen. Ohne diese Eindeutigkeit gilt nur ≤.', 'method-languages',
  {headers:['A \\ B','b','ab'],rows:[['ε','b','ab'],['a','ab','aab']]}),
 closure: guide('Stern, Plus und Sprachpotenzen an vollständigen Randfällen erklären.',
  ['Bestimme zuerst L⁰, L¹ und L².','Beim Stern ist nullmalige Verkettung erlaubt.','Beim Plus prüfe ausdrücklich, ob ε schon in L liegt.'],
  'L={a,bb}. Berechne L² und entscheide über ε und abb in L* und L⁺.',
  ['L² entsteht aus allen vier Paaren: {aa,abb,bba,bbbb}.','abb liegt schon in L² und damit sowohl in L⁺ als auch in L*.','ε liegt in L⁰={ε} und daher in L*.','Jeder Faktor aus L hat positive Länge. Also kann kein positives Produkt ε ergeben; hier gilt ε ∉ L⁺.'],
  'Was ändert sich bei L={ε,a}?',
  'Dann gehört ε schon zu L¹ und damit auch zu L⁺. Beide Abschlüsse sind {ε,a,aa,aaa,…}.', 'method-languages'),
 quotient: guide('Beim Rechtsquotienten alle möglichen Suffixe prüfen und unmögliche Paare begründen.',
  ['Nimm jedes x aus A und jedes z aus B.','Falls x auf z endet, entferne exakt dieses Suffix; sonst kein Ergebnis.','Ein ε-Suffix entfernt nichts. Doppelte Restwörter nur einmal aufnehmen.'],
  'A={ab,abb,b}, B={ε,b}. Gesucht sind alle w mit wz∈A für mindestens ein z∈B.',
  ['Für z=ε bleiben ab, abb und b unverändert.','Für z=b entstehen aus ab das Wort a, aus abb das Wort ab und aus b das Wort ε.','Die Vereinigung aller Ergebnisse ist {ε,a,b,ab,abb}.','„Nicht möglich“ würde heißen: Das gewählte z ist kein vollständiges Endstück des gewählten x.'],
  'Darf man aus ab mit dem Suffix a das Wort b erhalten?',
  'Nein. a steht am Anfang, nicht am Ende. Der Rechtsquotient entfernt ausschließlich vollständige Endstücke.', 'method-languages',
  {headers:['x aus A','z=ε','z=b'],rows:[['ab','ab','a'],['abb','abb','ab'],['b','b','ε']]}),
 regex: guide('Reguläre Ausdrücke entsprechend ihrer Bindungsreihenfolge lesen.',
  ['Markiere Klammern und Stern/Plus.','Fasse danach Verkettungen zusammen.','Lies die äußerste Vereinigung zuletzt.'],
  'Vergleiche r=(a|b)*a|b und s=(a|b)*(a|b).',
  ['r ist die Vereinigung von „endet auf a“ mit dem einzelnen Wort b.','s beschreibt einen beliebigen Anfang mit genau einem abschließenden Zeichen: alle nichtleeren Wörter.','bb liegt in s, aber weder endet es auf a noch ist es das einzelne b: bb ∉ L(r).','Damit sind die Ausdrücke verschieden. Ein Gegenwort genügt als Widerlegung.'],
  'Welche der beiden Sprachen enthält ε?',
  'Keine. Bei r ist ein Schluss-a oder das Wort b nötig; bei s erzwingt die letzte Klammer mindestens ein Zeichen.', 'method-regex'),
 construct: guide('Einen RegEx konstruieren und beide Richtungen seiner Korrektheit erklären.',
  ['Übersetze Pflichtzeichen und frei wählbare Bereiche.','Prüfe ε, ein kürzestes gültiges Wort und knappe Gegenbeispiele.','Erkläre, warum nichts Falsches erzeugt und nichts Richtiges ausgelassen wird.'],
  'Gesucht: Binärwörter mit genau zwei Einsen.',
  ['Die Pflichtzeichen sind zwei Einsen: 1 … 1.','Vor, zwischen und nach ihnen dürfen nur Nullen stehen: 0*10*10*.','Jedes erzeugte Wort besitzt genau die beiden ausgeschriebenen Einsen.','Umgekehrt zerfällt jedes Wort mit genau zwei Einsen in drei Nullblöcke um diese Einsen. 11 passt; ε, 1 und 111 passen nicht.'],
  'Warum ist (0|1)*11(0|1)* dafür zu weit?',
  'Der Ausdruck erlaubt zusätzliche Einsen und fordert außerdem benachbarte Einsen. Er akzeptiert 111 fälschlich und lehnt 101 fälschlich ab.', 'method-regex'),
 dfa: guide('Einen vollständigen DEA aus Zustandsbedeutungen konstruieren und an Läufen prüfen.',
  ['Formuliere, welche Information der Zustand nach jedem Präfix speichert.','Lege Start- und Endzustände fest.','Trage für jeden Zustand und jedes Zeichen genau einen Übergang ein.'],
  'Binärwörter sollen genau dann akzeptiert werden, wenn sie auf 0 enden.',
  ['N bedeutet „bisher leer oder letztes Zeichen 1“, Z bedeutet „letztes Zeichen 0“.','Start N; nur Z akzeptiert, denn ε endet nicht auf 0.','Eine 0 führt aus jedem Zustand nach Z, eine 1 aus jedem Zustand nach N.','Der Lauf für 010 ist N→Z→N→Z und akzeptiert erst nach dem letzten Zeichen.'],
  'Was geschieht bei 01, obwohl Z bereits besucht wurde?',
  'Nach der letzten 1 steht der Automat in N und lehnt ab. Ein Endzustand beendet den Lauf nicht vorzeitig.', 'method-dfa',
  {headers:['Zustand','0','1'],rows:[['→N','Z','N'],['*Z','Z','N']]}),
 parity: guide('Zustände als Restklassen verstehen und eine Invariante begründen.',
  ['Lege die gezählte Zeichenart und den Modulus fest.','Zustand rᵢ speichert den Rest i.','Gezählte Zeichen schalten weiter, andere lassen den Rest unverändert.'],
  'Die Anzahl der Einsen soll durch 3 teilbar sein.',
  ['Zustände r0,r1,r2; Start r0; F={r0}.','Bei 1: r0→r1→r2→r0. Bei 0 bleibt jeder Zustand gleich.','Für 10101: r0→r1→r1→r2→r2→r0. Drei Einsen führen zur Annahme.','ε wird ebenfalls akzeptiert, weil 0 durch 3 teilbar ist.'],
  'Warum braucht der Automat nicht die genaue Anzahl der Einsen?',
  'Für spätere Annahmeentscheidungen genügt der Rest modulo 3. Anzahlen mit gleichem Rest verhalten sich bei jedem weiteren Suffix gleich.', 'method-dfa'),
 alternate: guide('Ein Verbot im DEA durch einen Fangzustand dauerhaft speichern.',
  ['Unterscheide Anfang, letzte 0 und letzte 1.','Ein wiederholtes gleiches Nachbarzeichen führt in den Fehlerzustand.','Der Fehlerzustand hat für jedes Zeichen eine Schleife.'],
  'Erkenne Wörter ohne 00 und ohne 11 als Teilwort; ε ist erlaubt.',
  ['S ist der Anfang, Z bedeutet letzte 0, E letzte 1, X bedeutet „Verbot verletzt“.','S, Z und E akzeptieren; X nicht.','S:0→Z,1→E; Z:0→X,1→E; E:0→Z,1→X; X bleibt stets X.','0110 läuft S→Z→E→X→X. Das spätere 0 kann die bereits aufgetretene 11 nicht reparieren.'],
  'Warum dürfen Z und E trotz gleichem Akzeptanzstatus nicht verschmelzen?',
  'Das Restwort 0 unterscheidet sie: Von Z führt es nach X, von E nach Z. Die zukünftigen Annahmen sind verschieden.', 'method-dfa'),
 complement: guide('Eine Sprache durch Vervollständigen und Wechseln der Endzustände komplementieren.',
  ['Lege das Alphabet fest.','Ergänze fehlende Übergänge samt Fangzustand.','Ersetze F durch Q∖F und prüfe besonders ε.'],
  'Ein partieller DEA hat Start S, Endzustand A und nur S:0→A sowie A:0→A. Alphabet {0,1}.',
  ['Er erkennt die nichtleeren Nullwörter. Für 1 fehlen Übergänge.','Ergänze X: S und A gehen bei 1 nach X; X bleibt bei 0 und 1 in X.','Nach Komplementierung akzeptieren S und X; A nicht.','ε endet in S, 1 endet in X, 00 endet in A: Das Komplement nimmt die ersten beiden an und lehnt 00 ab.'],
  'Was ginge ohne Fangzustand beim Wort 1 schief?',
  'Der Lauf wäre weiterhin undefiniert und würde nicht akzeptieren. Das Wort müsste im Komplement aber enthalten sein.', 'method-dfa'),
 grammar: guide('Für dieselbe Sprache eine rechtslineare Grammatik und einen Automaten angeben.',
  ['Ordne jedem Automatenzustand eine Variable zu.','Ein Übergang A mit a nach B wird zur Regel A→aB.','Für Endzustände ergänze eine ε-Regel.'],
  'Gesucht ist die Sprache 0*1: beliebig viele Nullen, genau eine abschließende Eins.',
  ['Eine Grammatik ist S→0S | 1F, F→ε.','Die Ableitung von 001 lautet S⇒0S⇒00S⇒001F⇒001.','Ein vollständiger DEA hat S, F und X: S:0→S,1→F; F und X gehen bei jedem Zeichen nach X. Nur F akzeptiert.','Eine Eins ist Pflicht. Weitere Zeichen danach sind verboten. Das passt zugleich zur Grammatik und zu 0*1.'],
  'Warum ist S→0S | 1S | ε zu weit?',
  'Diese Grammatik erzeugt alle Binärwörter, auch ε oder 11. Sie erzwingt keine einzige abschließende Eins.', 'method-equivalence'),
 hierarchy: guide('Sprachklasse und geeignetes Maschinenmodell mit einem trennenden Beispiel verbinden.',
  ['Frage, welche unbeschränkte Information gespeichert werden muss.','Nenne ein Modell, das ausreicht.','Für die kleinste Klasse begründe auch, warum die nächstkleinere nicht reicht.'],
  'Ordne {aⁿbⁿ:n≥0} ein.',
  ['Ein Keller speichert pro a einen Marker und entfernt pro b einen: Ein NPDA reicht.','Die Grammatik S→aSb | ε erzeugt genau gleich große a- und b-Blöcke.','Nichtregularität folgt zum Beispiel aus dem Pumping-Lemma. Endlich viele Zustände reichen nicht für den unbeschränkten Blockabgleich.','Die kleinste Chomsky-Klasse ist deshalb Typ 2. Die Sprache ist zugleich Typ 1 und Typ 0.'],
  'Bedeutet „Typ 2“ automatisch exakt n³ Schritte?',
  'Nein. Für eine feste CNF-Grammatik bietet CYK die allgemeine Zeitschranke O(n³); einzelne Sprachen und andere Verfahren können schneller sein.', 'method-hierarchy',
  {headers:['Typ','Modell','Beispiel'],rows:[['3 · regulär','DEA / NEA','a*'],['2 · kontextfrei','NPDA','{aⁿbⁿ}'],['1 · kontextsensitiv','linear beschränkte NTM','{aⁿbⁿcⁿ}'],['0 · RE','TM als Erkenner','Halteproblem']]}),
 transfer: guide('Zwischen Erkennen, Umformen und inhaltlichem Prüfen unterscheiden.',
  ['Formuliere die konkrete Eingabe-Ausgabe-Aufgabe.','Nutze für eine reguläre Syntax einen endlichen Automaten.','Prüfe, ob darüber hinaus Ausgabe, Speicher oder externe Daten nötig sind.'],
  'Eine Kennung besteht aus # und mindestens einem Binärzeichen. Danach soll # entfernt werden.',
  ['Die Syntaxsprache ist #(0|1)(0|1)*. Ein DEA kann ihre Zugehörigkeit prüfen.','Die Lesezeit eines festen DEA ist linear in der Wortlänge.','Der gewöhnliche DEA ist ein Erkenner und liefert nur Annahme/Ablehnung. Er schreibt keine neue Eingabe.','Für das Entfernen kann ein Transduktor oder gewöhnlicher String-Algorithmus die Zeichen nach # ausgeben. Daraus folgt keine schwierige Berechnungsaufgabe.'],
  'Genügt das Bestehen der Syntaxprüfung als Nachweis, dass eine Kennung existiert?',
  'Nein. Für die Existenzprüfung braucht man zusätzlich die Menge tatsächlich vergebener Kennungen, etwa eine Datenbank.', 'method-equivalence'),
 nea: guide('Einen NEA vollständig determinisieren: Mengen, Übergänge und Endzustände dokumentieren.',
  ['Starte mit der ε-Hülle des Startzustands.','Für jedes Zeichen: alle Nachfolger vereinigen, danach ε-Hülle bilden.','Neue Mengen als eigene Zustände aufnehmen, bis keine neue Menge entsteht.'],
  'NEA ohne ε: s:0→{s,p},1→{s}; p:1→{f}; f ohne Übergänge. Start s, F={f}.',
  ['Startmenge A={s}. Bei 0 entsteht B={s,p}, bei 1 wieder A.','Aus B entsteht bei 0 wieder B und bei 1 die neue Menge C={s,f}.','Aus C entsteht bei 0 B und bei 1 A. Damit sind alle erreichbaren Mengen verarbeitet.','Nur C akzeptiert, weil genau diese Menge f enthält. Der DEA erkennt Wörter mit Endung 01.'],
  'Muss man bei drei NEA-Zuständen immer alle acht Teilmengen zeichnen?',
  'Nein. Es gibt höchstens 2³ mögliche Mengen, aber nur erreichbare Mengen sind nötig. Hier sind es drei.', 'method-nea',
  {headers:['DEA-Zustand','0','1'],rows:[['→A={s}','B','A'],['B={s,p}','B','C'],['*C={s,f}','B','A']]}),
 minimize: guide('Einen DEA mit stabiler Partition und vollständigem Quotientenautomaten minimieren.',
  ['Entferne unerreichbare Zustände.','Teile in Endzustände und Nichtendzustände.','Vergleiche Nachfolgerklassen, verfeinere bis zur Stabilität und konstruiere Klassenzustände.'],
  'Start A, F={D}; Übergänge (0,1): A→(B,C), B→(D,C), C→(B,C), D→(D,C).',
  ['Alle vier Zustände sind erreichbar. P₀={{D},{A,B,C}}.','B führt bei 0 in die Endklasse, A und C nicht. Also P₁={{D},{B},{A,C}}.','A und C führen beide bei 0 nach {B} und bei 1 nach {A,C}. Keine weitere Trennung: P₁ ist stabil.','Startklasse {A,C}, Endklasse {D}. D gegen andere trennt ε; B gegen A/C trennt 0. Damit sind alle verbliebenen Klassen unterscheidbar.'],
  'Reicht eine einzige Runde ohne Vergleich aller Zeichen?',
  'Nein. Alle Alphabetzeichen müssen geprüft werden, und nach jeder Aufspaltung muss mit den neuen Klassen erneut verglichen werden.', 'method-minimize',
  {headers:['Klasse','0','1'],rows:[['→{A,C}','{B}','{A,C}'],['{B}','{D}','{A,C}'],['*{D}','{D}','{A,C}']]}),
 pumping: guide('Einen Nichtregularitätsbeweis mit der richtigen Quantorenreihenfolge schreiben.',
  ['Nimm Regularität an und erhalte eine unbekannte Pumpinglänge p.','Wähle ein Wort abhängig von p.','Behandle jede erlaubte Zerlegung und finde eine verletzende Pumpzahl.'],
  'Zeige: L={aⁿb²ⁿ:n≥1} ist nicht regulär.',
  ['Unter der Annahme der Regularität existiert eine Pumpinglänge p. Wähle w=aᵖb²ᵖ.','Für jede Zerlegung w=xyz mit |xy|≤p und |y|≥1 liegt y vollständig im a-Block: y=aᵏ mit k≥1.','Pumpe mit i=0. Dann enthält xz nur p−k a, aber weiterhin 2p b.','Die Bedingung „doppelt so viele b“ ist verletzt: 2(p−k)≠2p. Das widerspricht dem Lemma.'],
  'Warum wäre „Ich wähle y=a“ als alleiniger Beweis unzureichend?',
  'Die Gegenseite darf jede gültige Zerlegung wählen. Du musst alle k≥1, die durch die Bedingungen möglich sind, abdecken.', 'method-pumping'),
 cnf: guide('CNF schrittweise herstellen und Mehrdeutigkeit über verschiedene Bäume nachweisen.',
  ['Behandle ε- und Kettenregeln; bei Bedarf einen neuen Start einführen.','Ersetze Terminale in längeren rechten Seiten durch Variablen.','Zerlege lange rechte Seiten binär und prüfe jede Regel.'],
  'Bringe S→aSb | ab in CNF für die nichtleere Sprache {aⁿbⁿ:n≥1}.',
  ['Setze A→a und B→b. Dann wird S→ASB | AB.','Führe C→SB ein und ersetze ASB durch AC.','Für die strenge Startkonvention nimm S₀→AC | AB, S→AC | AB, C→SB, A→a, B→b. S₀ kommt rechts nicht vor.','Jede Regel hat jetzt die Form Variable→zwei Variablen oder Variable→ein Terminal. Die Basis ab bleibt erhalten.'],
  'Sind verschiedene Reihenfolgen beim Ersetzen unabhängiger Variablen schon Mehrdeutigkeit?',
  'Nein. Sie können denselben Syntaxbaum beschreiben. Mehrdeutigkeit benötigt zwei verschiedene Bäume für dasselbe Terminalwort.', 'method-cnf'),
 cyk: guide('Jede Trennstelle und jedes geordnete Variablenpaar einer CYK-Zelle prüfen.',
  ['Basis: alle Variablen mit passender Terminalregel eintragen.','Von kurzen zu langen Teilwörtern arbeiten. Für jede Trennstelle das kartesische Produkt der beiden Zellen prüfen.','Alle gefundenen linken Regelseiten sammeln; zum Schluss Startsymbol prüfen.'],
  'Start S; Regeln S→AB | AC, C→SB, A→a, B→b. Prüfe aabb.',
  ['Länge 1: {A}, {A}, {B}, {B}. Länge 2: aa→∅, ab→{S}, bb→∅.','Für aab ergeben a|ab das Paar AS (keine Regel) und aa|b keine Paare. Also ∅.','Für abb liefert ab|b das Paar SB und damit C. Also Länge 3: ∅, {C}.','Für aabb liefert a|abb das Paar AC und damit S. Die anderen Trennstellen liefern nichts. Oben steht S, also wird aabb akzeptiert.','Eine Ableitung ist S⇒AC⇒ASB⇒AABB⇒aABB⇒aaBB⇒aabB⇒aabb.'],
  'Links steht {A,S}, rechts {B,C}. Wie viele Paare musst du bei dieser Trennstelle prüfen?',
  'Vier: AB, AC, SB, SC. Es ist |links|·|rechts|, keine Auswahl ohne Reihenfolge. Nur Paare mit passender rechter Regelseite liefern eine Variable.', 'method-cyk',
  {headers:['Teilwortlänge','Zellen von links nach rechts'],rows:[['1','{A} · {A} · {B} · {B}'],['2','∅ · {S} · ∅'],['3','∅ · {C}'],['4','{S}']]}),
 stack: guide('Den benötigten Kellerinhalt, Phasenwechsel und das Akzeptanzkriterium erklären.',
  ['Gib jedem Marker eine Bedeutung.','Beschreibe, wann ein Marker abgelegt oder entfernt wird.','Prüfe falsche Reihenfolge, zu viele Schlusszeichen und unvollständigen Abbau.'],
  'Erkenne korrekt geschachtelte Klammerwörter mit einem Klammerpaar.',
  ['Für jede öffnende Klammer wird ein Marker auf den Keller gelegt.','Für jede schließende Klammer wird ein Marker entfernt. Fehlt einer, wird abgelehnt.','Nach vollständiger Eingabe muss nur das Bodensymbol übrig sein. (()()) funktioniert; ())( scheitert schon bei der dritten Klammer.','Dieser Ablauf ist deterministisch. Klammerwörter sind also ein Beispiel für eine nichtreguläre, aber deterministisch kontextfreie Sprache.'],
  'Beweist dieses Beispiel, dass DPDA und NPDA gleich mächtig sind?',
  'Nein. Es zeigt nur, dass diese eine Sprache deterministisch erkannt wird. Allgemein ist DCFL eine echte Teilklasse von CFL; unmarkierte Palindrome liefern ein Gegenbeispiel.', 'method-stack'),
 tm: guide('Konfigurationen fehlerfrei fortschreiben und das Verhalten einer Maschine erklären.',
  ['Schreibe den Zustand direkt vor die aktuell gelesene Zelle.','Führe Lesen, Schreiben, Bewegung und Zustandswechsel in einem Schritt aus.','Erkläre pro Phase eine Invariante und behandle Randfälle.'],
  'Eine Maschine ersetzt beim Rechtslauf jede 0 durch 1, lässt 1 stehen und hält auf □. Eingabe 010.',
  ['Übergänge: δ(q,0)=(q,1,R), δ(q,1)=(q,1,R), δ(q,□)=(h,□,N).','Anfang: [q]010□. Nach dem ersten Schritt: 1[q]10□.','Danach: 11[q]0□, dann 111[q]□, dann 111[h]□.','Links vom Kopf stehen nur Einsen; rechts ist die Eingabe noch unverändert. Der Kopf bewegt sich bis zum ersten Blank stets nach rechts.','Für eine endliche Eingabe hält die Maschine nach n+1 Übergängen. Bei ε erfolgt sofort der Blank-Schritt.'],
  'Sind „erste fünf Konfigurationen“ dasselbe wie „fünf Übergänge“?',
  'Nein. Zählt die Anfangskonfiguration mit, liefern fünf Konfigurationen nur vier Übergänge. Gib deine Zählkonvention ausdrücklich an.', 'method-tm'),
 np: guide('Ein Graphenproblem modellieren und eine vorgeschlagene Lösung vollständig prüfen.',
  ['Bestimme Knoten, Kanten und den Schwellenwert.','Formuliere eine Ja/Nein-Frage.','Prüfe jede erforderliche Bedingung des Zertifikats; begründe Optima zusätzlich durch eine untere oder obere Schranke.'],
  'Kameras an Kreuzungen sollen jede Straße erfassen. Graph: Dreieck a–b–c–a und zusätzliche Straße c–d.',
  ['Die Auswahl ist ein Vertex Cover: Jede Kante braucht mindestens einen ausgewählten Endpunkt.','{a,c} deckt ab, bc, ca und cd. Also reichen zwei Kameras.','Eine Kamera genügt nicht: Im Dreieck bleibt gegenüber jedem einzelnen Knoten eine unberührte Kante. Das Optimum ist 2.','Zur Prüfung einer gegebenen Auswahl markierst du ihre Knoten und gehst jede Kante durch. Das benötigt O(|V|+|E|) mit geeigneter Darstellung.'],
  'Reicht es, wenn jeder nicht ausgewählte Knoten einen ausgewählten Nachbarn hat?',
  'Nein. Das beschreibt eine dominierende Menge. Für Vertex Cover müssen auch Kanten zwischen zwei nicht ausgewählten Knoten ausgeschlossen sein.', 'method-np'),
 reduction: guide('Die Richtung einer Reduktion und beide Richtungen der Lösungserhaltung erklären.',
  ['Für Schwere: vom bekannten schweren Problem zum neuen Problem übersetzen.','Definiere die Transformation einschließlich Parameter.','Begründe Ja genau dann Ja und polynomialen Aufwand; zeige für NP-Vollständigkeit zusätzlich NP-Zugehörigkeit.'],
  'Reduziere CLIQUE auf VERTEX COVER.',
  ['Für (G,k) bilde den Komplementgraphen H und setze den neuen Grenzwert |V|−k.','Eine k-Clique C in G ist eine unabhängige Menge in H. Daher berührt V∖C jede Kante von H.','Umgekehrt: Ist D ein Cover in H mit |D|≤|V|−k, ist V∖D unabhängig in H und damit eine Clique von mindestens k Knoten in G.','Die Komplementbildung prüft höchstens quadratisch viele Knotenpaare. Der Übersetzer ist polynomial.'],
  'Was folgt aus A≤ₚB und B∈P?',
  'Dann liegt auch A in P: Eingabe übersetzen und B lösen. Aus A∈P allein folgt dagegen nichts Entsprechendes über B.', 'method-reduction'),
 decidable: guide('Entscheidung, Semi-Entscheidung und Rice mit konkreten Halteforderungen abgrenzen.',
  ['Nenne Eingabe und Ja/Nein-Eigenschaft.','Frage, ob das Verfahren auf beiden Antwortseiten hält.','Bei Rice: semantische und nichttriviale Eigenschaft partiell berechenbarer Funktionen prüfen.'],
  'L={<M,w>:M hält auf w}. Warum genügt Simulation nur für Semi-Entscheidung?',
  ['Simuliere M auf w. Hält M, kannst du nach endlich vielen Schritten Ja sagen.','Läuft M endlos, wartet die Simulation ebenfalls endlos. Sie liefert dann kein Nein.','Ein Zeitlimit hilft nicht allgemein: Eine Maschine kann erst nach jedem vorgegebenen Limit halten.','Ein Entscheider für diese allgemeine Frage existiert nicht. Einzelne einfache Programme lassen sich trotzdem analysieren.'],
  'Gilt Rice für „Der Programmtext enthält eine Schleife“?',
  'Nein. Das ist syntaktisch und lässt sich am endlichen Text prüfen. Rice betrifft nichttriviale Eigenschaften der berechneten Funktion, unabhängig von ihrer Schreibweise.', 'method-decidable')
};
