import {questions,allTopics,lessonById} from './curriculum.js';
import {levels,kinds} from './topics.js';
import {filterQuestions,missions,missionProgress,confidenceStats} from './practice.js';
export const topicHref=id=>lessonById[id]?`#lesson/${id}`:`#topic/${id}`;
export function arenaView({state,filters,esc,icon,head,bar}){
 const pool=filterQuestions(filters),cal=confidenceStats(state),solved=questions.filter(q=>state.results[q.id]?.successes.length).length;
 return `${head('DEINE TRAININGSARENA','Jede Runde bringt dich weiter.','Erst abrufen, dann nachschauen. Wechsle zwischen Verständnis, Rechnen und Transfer.',`<span class="pill purple">${questions.length} Aufgaben · ${allTopics.length} Themen</span>`)}
 <div class="inline-actions arena-links"><a href="#review" class="btn secondary">${icon('repeat')} Fehler & fällige Wiederholungen</a><a href="#lab" class="btn secondary">${icon('flask')} Frei experimentieren</a><a href="#exams" class="btn secondary">${icon('target')} Probeklausuren</a></div>
 <div class="grid dashboard-grid"><section class="card"><div class="card-title"><h2>Deine nächste Runde</h2><span class="pill gray">${pool.length} passend</span></div><div class="practice-filters">
 <label class="field">Thema<select id="practice-topic" data-practice-filter="topic"><option value="all">Alle Themen mischen</option>${allTopics.map(t=>`<option value="${t.id}" ${filters.topic===t.id?'selected':''}>W${t.week} · ${esc(t.title)}</option>`).join('')}</select></label>
 <label class="field">Stufe<select data-practice-filter="level"><option value="all">Alle Stufen</option>${Object.entries(levels).map(([v,l])=>`<option value="${v}" ${String(filters.level)===v?'selected':''}>${v} · ${l}</option>`).join('')}</select></label>
 <label class="field">Aufgabenart<select data-practice-filter="kind"><option value="all">Alles kombinieren</option>${Object.entries(kinds).map(([v,l])=>`<option value="${v}" ${filters.kind===v?'selected':''}>${l}</option>`).join('')}</select></label>
 <label class="field">Rundenlänge<select data-practice-filter="count">${[5,10,20].map(n=>`<option value="${n}" ${Number(filters.count)===n?'selected':''}>${n} Aufgaben</option>`).join('')}</select></label></div>
 <button class="btn" data-action="practice-start" ${pool.length?'':'disabled'}>Runde mit ${Math.min(pool.length,Number(filters.count))} Aufgaben starten ${icon('arrow')}</button>${!pool.length?'<p class="help" role="status">Für diese Kombination gibt es keine Aufgaben. Wähle eine andere Stufe oder Aufgabenart.</p>':''}
 <p class="help" style="margin-top:18px">Deine offenen Fehler kommen zuerst, danach fällige und neue Aufgaben. Die Runde mischt verschiedene Aufgabentypen, statt nur Zahlen desselben Beispiels auszutauschen. Für einen ruhigen Einstieg wähle ein Thema und Stufe 1.</p></section>
 <aside class="card"><div class="eyebrow">DEIN ECHTER FORTSCHRITT</div><div class="score">${solved}<span> / ${questions.length}</span></div><p>Verschiedene Aufgaben ohne Hinweis gelöst.</p>${bar(Math.round(solved/questions.length*100),true)}<div class="separator"></div><h3>Wie sicher bist du dir?</h3><p class="small muted">Vor der Auflösung kannst du deine Sicherheit einschätzen. „Sicher, aber falsch“ zeigt oft ein Missverständnis, das sich gezielt klären lässt.</p><span class="pill ${cal.wrongSure?'gray':'purple'}">${cal.wrongSure} von ${cal.sure} sicheren Antworten waren falsch</span><p class="help">Alle erfassten Versuche, kein Urteil über deine Fähigkeiten. Die Einschätzung bleibt freiwillig.</p></aside></div>
 <div class="section-heading"><h2>Missionen mit einem klaren Ende</h2><a href="#achievements">Pokale ansehen →</a></div><div class="grid mission-grid">${missions.map(m=>{const done=missionProgress(state,m),won=done>=m.target;return `<section class="card mission ${won?'mission-done':''}"><span class="pill ${won?'purple':'gray'}">${won?'✓ GESCHAFFT':`${Math.min(done,m.target)} / ${m.target}`}</span><h3>${m.title}</h3><p class="small muted">${m.text}</p>${bar(Math.min(100,Math.round(done/m.target*100)))}<button class="btn ${won?'ghost':'secondary'}" data-action="mission" data-id="${m.id}">${won?'Weiter festigen':'Mission starten'} ${icon('arrow')}</button></section>`;}).join('')}</div>
 <div class="section-heading"><h2>Alle Themen zum Nachschlagen & Üben</h2></div><div class="grid topic-library">${allTopics.map(t=>{const qs=questions.filter(q=>q.lesson===t.id),done=qs.filter(q=>state.results[q.id]?.successes.length).length;return `<article class="card"><div class="eyebrow">WOCHE ${t.week} · ${qs.length} AUFGABEN</div><h3>${esc(t.title)}</h3><p class="help">${done} verschiedene Aufgaben ohne Hinweis gelöst</p><div class="inline-actions"><a href="${topicHref(t.id)}" class="btn ghost">${t.week===1?'Lektion':'Kurzüberblick'}</a><a href="#practice/${t.id}" class="btn secondary">Üben ${icon('arrow')}</a></div></article>`;}).join('')}</div>`;
}
export function topicView(t,{esc,icon,head}){
 const count=questions.filter(q=>q.lesson===t.id).length;
 return `<a href="#practice" class="back-link">${icon('back')} Zur Trainingsarena</a>${head(`WOCHE ${t.week} · KURZÜBERBLICK`,esc(t.title),esc(t.intro))}<div class="reading-layout"><article class="reading"><section class="reading-section"><h2>So gehst du vor</h2><ol class="topic-steps">${t.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></section><div class="example"><h3>Ein Beispiel</h3><p>${esc(t.example)}</p></div><div class="callout"><strong>Typischer Denkfehler</strong>${esc(t.trap)}</div><div class="reading-footer"><a href="#practice/${t.id}" class="btn">${count} Aufgaben erkunden ${icon('arrow')}</a><button class="btn secondary" data-action="topic-practice" data-id="${t.id}">5 Aufgaben direkt starten</button></div></article><aside class="card sticky"><div class="eyebrow">ABRUFEN STATT NUR LESEN</div><p>Decke die Erklärung ab. Beschreibe das Verfahren mit eigenen Worten. Löse danach eine Aufgabe ohne Vorlage und erkläre, warum dein Ergebnis stimmt.</p><div class="separator"></div><p class="help">${esc(t.source)}</p><p class="help">Dieser Überblick und die Übungen ergänzen die ausführlichen Vorlesungsfolien. Der Wochenplan enthält weitere handschriftliche Aufgaben.</p></aside></div>`;
}
