import {learningGoal,lessonGuideView} from './lesson-guide-view.js';
import {questions,allTopics,lessonById} from './curriculum.js';
import {levels,kinds} from './topics.js';
import {filterQuestions,practiceCount,questionStatus,missions,missionProgress} from './practice.js';
import {lessonProgress} from './progress.js';
export const topicHref=id=>lessonById[id]?`#lesson/${id}`:`#topic/${id}`;
export function arenaView({state,filters,selected=new Set(),pickerOpen=false,resume=null,esc,icon,head,bar}){
 const pool=filterQuestions(filters,questions,state),solved=questions.filter(q=>state.results[q.id]?.successes.length).length;
 const selectedCount=pool.filter(q=>selected.has(q.id)).length;
 const topicProgress=filters.topic!=='all'?lessonProgress(state,filters.topic):null;
 return `${head('DEINE TRAININGSARENA','Jede Runde bringt dich weiter.','Erst abrufen, dann nachschauen. Wechsle zwischen Verständnis, Rechnen und Transfer.',`<span class="pill purple">${questions.length} Aufgaben · ${allTopics.length} Themen</span>`)}
 ${resume?`<section class="card practice-resume"><div><h2>Deine Runde läuft noch</h2><p class="help">${esc(resume.title)} · ${resume.answers.length} von ${resume.items.length} bearbeitet. Geprüfte Antworten sind bereits gespeichert.</p></div><a href="#quiz" class="btn">Runde fortsetzen ${icon('arrow')}</a></section>`:''}
 <div class="inline-actions arena-links"><a href="#review" class="btn secondary">${icon('repeat')} Fehler & fällige Wiederholungen</a><a href="#lab" class="btn secondary">${icon('flask')} Frei experimentieren</a><a href="#exams" class="btn secondary">${icon('target')} Probeklausuren</a></div>
 <div class="grid dashboard-grid"><section class="card"><div class="card-title"><h2>Deine nächste Runde</h2><span class="pill gray">${pool.length} passend</span></div><div class="practice-filters">
 <label class="field">Thema<select id="practice-topic" data-practice-filter="topic"><option value="all">Alle Themen mischen</option>${allTopics.map(t=>`<option value="${t.id}" ${filters.topic===t.id?'selected':''}>W${t.week} · ${esc(t.title)}</option>`).join('')}</select></label>
 <label class="field">Stufe<select data-practice-filter="level"><option value="all">Alle Stufen</option>${Object.entries(levels).map(([v,l])=>`<option value="${v}" ${String(filters.level)===v?'selected':''}>${v} · ${l}</option>`).join('')}</select></label>
 <label class="field">Aufgabenart<select data-practice-filter="kind"><option value="all">Alles kombinieren</option>${Object.entries(kinds).map(([v,l])=>`<option value="${v}" ${filters.kind===v?'selected':''}>${l}</option>`).join('')}</select></label>
 <label class="field">Lernstand<select data-practice-filter="status">${[['all','Alle Aufgaben'],['open','Noch offen oder erneut üben'],['new','Noch nie bearbeitet'],['solved','Ohne Hilfe gelöst'],['due','Heute fällige Wiederholungen']].map(([v,l])=>`<option value="${v}" ${filters.status===v?'selected':''}>${l}</option>`).join('')}</select></label>
 <label class="field">Rundenlänge<select data-practice-filter="count">${[5,10,20,40,'all'].map(n=>`<option value="${n}" ${String(filters.count)===String(n)?'selected':''}>${n==='all'?`Alle ${pool.length} passenden Aufgaben`:`${n} Aufgaben`}</option>`).join('')}</select></label>
 <label class="field practice-search">Aufgaben suchen<input type="search" data-practice-filter="search" value="${esc(filters.search||'')}" placeholder="Begriff oder Aufgaben-ID · mit Enter suchen"></label></div>
 <div class="inline-actions"><button class="btn" data-action="practice-start" ${pool.length?'':'disabled'}>Runde mit ${practiceCount(filters.count,pool.length)} Aufgaben starten ${icon('arrow')}</button><button class="btn ghost" data-action="practice-reset">Filter zurücksetzen</button></div>${!pool.length?'<p class="help" role="status">Keine passenden Aufgaben. Setze die Filter zurück oder ändere deine Suche.</p>':''}
 <p class="help" style="margin-top:18px">Deine offenen Fehler kommen zuerst, danach fällige und neue Aufgaben. Die Runde mischt verschiedene Aufgabentypen, statt nur Zahlen desselben Beispiels auszutauschen. Für einen ruhigen Einstieg wähle ein Thema und Stufe 1.</p></section>
 <aside class="card"><div class="eyebrow">${topicProgress?'DEIN THEMA':'DEIN FORTSCHRITT'}</div><div class="score">${topicProgress?.solved??solved}<span> / ${topicProgress?.total??questions.length}</span></div><p>Verschiedene Aufgaben ohne Hinweis gelöst.</p>${bar(Math.round((topicProgress?.solved??solved)/(topicProgress?.total??questions.length)*100),true)}<div class="separator"></div><h3>Jede Antwort zählt sofort.</h3><p class="small muted">✓ = ohne Hilfe gelöst. Nach einem Hinweis bleibt die Aufgabe zum selbstständigen Wiederholen offen.</p>${topicProgress&&lessonById[filters.topic]?`<p class="completed-stamp">${topicProgress.completed?'✓ Lektion abgeschlossen':`Noch ${topicProgress.remaining} verschiedene richtige Aufgaben bis zum Lektionshaken.`}</p>`:''}<p class="help">Der Lektionshaken entsteht nach 7 verschiedenen richtigen Aufgaben ohne Hilfe – auch über mehrere Runden. Bereits erreichte Haken bleiben erhalten. „Sicher“ verlangt zusätzlich Übung an verschiedenen Tagen.</p></aside></div>
 <details class="card task-picker" id="practice-picker" ${pickerOpen?'open':''}><summary>Aufgaben selbst auswählen <span class="pill gray">${pool.length} verfügbar · ${selectedCount} ausgewählt</span></summary><p class="help">Alle Treffer sind auswählbar, ohne Begrenzung. Die Auswahl gilt für die aktuellen Filter. Du kannst jede Aufgabe auch einzeln starten.</p><div class="task-picker-actions"><button class="btn secondary" data-action="practice-select-all" ${pool.length?'':'disabled'}>Alle ${pool.length} auswählen</button><button class="btn ghost" data-action="practice-select-none">Auswahl leeren</button><button class="btn" data-action="practice-selected" ${selectedCount?'':'disabled'}>Auswahl starten (${selectedCount}) ${icon('arrow')}</button></div><div class="task-list">${pool.map(q=>{const status=questionStatus(state,q.id),solved=!!state.results[q.id]?.successes.length;return `<div class="task-row"><label><input type="checkbox" data-practice-select="${q.id}" ${selected.has(q.id)?'checked':''}><span><span class="task-meta">${esc(allTopics.find(t=>t.id===q.lesson)?.title)} · Stufe ${q.level} · ${esc(kinds[q.kind])}</span><span class="task-prompt">${esc(q.prompt)}</span><span class="task-meta">${solved?'✓ Ohne Hilfe gelöst':status==='new'?'○ Noch nicht bearbeitet':'↻ Noch selbstständig üben'}${solved&&status==='open'?' · Erneut üben':''} · ${esc(q.id)}</span></span></label><button class="btn ghost" data-action="practice-single" data-id="${q.id}" aria-label="Aufgabe ${q.id} einzeln üben">Üben ${icon('arrow')}</button></div>`;}).join('')||'<p class="help">Keine Aufgaben für diese Filter.</p>'}</div></details>
 <div class="section-heading"><h2>Missionen mit einem klaren Ende</h2><a href="#achievements">Pokale ansehen →</a></div><div class="grid mission-grid">${missions.map(m=>{const done=missionProgress(state,m),won=done>=m.target;return `<section class="card mission ${won?'mission-done':''}"><span class="pill ${won?'purple':'gray'}">${won?'✓ GESCHAFFT':`${Math.min(done,m.target)} / ${m.target}`}</span><h3>${m.title}</h3><p class="small muted">${m.text}</p>${bar(Math.min(100,Math.round(done/m.target*100)))}<button class="btn ${won?'ghost':'secondary'}" data-action="mission" data-id="${m.id}">${won?'Weiter festigen':'Mission starten'} ${icon('arrow')}</button></section>`;}).join('')}</div>
 <div class="section-heading"><h2>Alle Themen zum Nachschlagen & Üben</h2></div><div class="grid topic-library">${allTopics.map(t=>{const p=lessonProgress(state,t.id);return `<article class="card"><div class="eyebrow">WOCHE ${t.week} · ${p.total} AUFGABEN</div><h3>${esc(t.title)}</h3><p class="help">${p.solved} verschiedene Aufgaben ohne Hinweis gelöst</p>${bar(Math.round(p.solved/p.total*100),true)}${p.completed?'<p class="completed-stamp">✓ Lektion abgeschlossen</p>':''}<div class="inline-actions"><a href="${topicHref(t.id)}" class="btn ghost">Lektion öffnen</a><a href="#practice/${t.id}" class="btn secondary">Alle ${p.total} Aufgaben ${icon('arrow')}</a></div></article>`;}).join('')}</div>`;
}
export function topicView(t,{esc,icon,head}){
 const count=questions.filter(q=>q.lesson===t.id).length;
 return `<a href="#practice" class="back-link">${icon('back')} Zur Trainingsarena</a>${head(`WOCHE ${t.week} · VERTIEFUNG`,esc(t.title),esc(t.intro))}<div class="reading-layout"><article class="reading">${learningGoal(t.id,esc)}<section class="reading-section"><h2>So gehst du vor</h2><ol class="topic-steps">${t.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></section><div class="example"><h3>Ein Beispiel</h3><p>${esc(t.example)}</p></div><div class="callout"><strong>Typischer Denkfehler</strong>${esc(t.trap)}</div>${lessonGuideView(t.id,esc)}<div class="reading-footer"><a href="#practice/${t.id}" class="btn">${count} Aufgaben erkunden ${icon('arrow')}</a><button class="btn secondary" data-action="topic-practice" data-id="${t.id}">5 Aufgaben direkt starten</button></div></article><aside class="card sticky"><div class="eyebrow">ABRUFEN STATT NUR LESEN</div><p>Decke die Erklärung ab. Beschreibe das Verfahren mit eigenen Worten. Löse danach eine Aufgabe ohne Vorlage und erkläre, warum dein Ergebnis stimmt.</p><div class="separator"></div><p class="help">${esc(t.source)}</p><p class="help">Diese Vertiefung und die Übungen ergänzen die ausführlichen Vorlesungsfolien. Der Wochenplan enthält weitere handschriftliche Aufgaben.</p></aside></div>`;
}
