import {questionDfaFeedback} from './dfa-view.js';
import {hintsFor,inputSymbols,answerText} from './training-hints.js';
import {topicById,lessonById} from './curriculum.js';
import {lessonProgress} from './progress.js';

export function trainingQuestion(session,{state,esc,icon,bar,symbolKeyboard,explainPanel,bossLives}){
 const q=session.items[session.index],f=session.feedback,isCheck=session.type==='check',boss=session.type==='boss';
 const hints=hintsFor(q),shown=session.hintCount||0,p=lessonProgress(state,q.lesson);
 const actions=f
  ?`<button class="btn" data-action="next-question">${boss&&!session.lives?'Kampf beenden':session.index+1===session.items.length?'Runde abschließen':'Nächste Aufgabe'} ${icon('arrow')}</button><button class="btn ghost" data-action="explain" aria-expanded="${!!session.explain}">${session.explain?'Erklärung ausblenden':'Warum? Genauer erklären'}</button>`
  :`<button class="btn" data-action="submit-answer">${isCheck?'Antwort festhalten':'Ergebnis prüfen'} ${icon('check')}</button>${!isCheck&&!boss?`<button class="btn secondary" data-action="hint" ${shown>=hints.length?'disabled':''}>${shown===0?'Hinweis geben':shown===hints.length-1?'Lösungsweg zeigen':shown>=hints.length?'Alle Hilfen geöffnet':'Nächster Hinweis'}${shown?` (${Math.min(shown+1,hints.length)}/${hints.length})`:''}</button>`:''}<button class="btn ghost" data-action="skip">Weiß ich noch nicht</button>`;
 const symbols=inputSymbols(q);
 const exampleLetters=symbols.includes('a')&&!symbols.includes('0');
 return `<div class="quiz"><div class="quiz-top"><a href="${session.lesson?'#lesson/'+session.lesson:boss?'#play':'#practice'}" class="back-link" style="margin:0">${icon('back')} ${session.lesson?'Zur Lektion':boss?'Kampf verlassen':'Zur Trainingsarena'}</a><span class="quiz-status">${boss?`<span class="hearts" aria-label="${session.lives} von ${bossLives} Leben">${Array.from({length:bossLives},(_,i)=>`<span class="heart ${i<session.lives?'':'lost'}"></span>`).join('')}</span>`:''}${session.combo>=2?`<span class="combo">${icon('flame')} ${session.combo}er-Kette</span>`:''}<span>${session.index+1} / ${session.items.length}</span></span></div>
 ${bar(Math.round(session.answers.length/session.items.length*100),true)}
 <section class="card quiz-card"><div class="eyebrow">${esc(topicById[q.lesson].title)} · ${q.type==='choice'?'Eine Antwort wählen':q.type==='set'?'Menge berechnen':q.type==='regex'?'RegEx konstruieren':'Selbst berechnen'}</div><h1 id="question-title" tabindex="-1">${esc(q.prompt)}</h1>
 ${q.type==='choice'?`<div class="answers" role="group" aria-labelledby="question-title">${session.options[q.id].map(({text,index},i)=>`<button class="answer ${session.selected===index?'selected':''} ${f&&index===q.answer?'correct':''} ${f&&session.selected===index&&!f.correct?'wrong':''}" data-action="select-answer" data-index="${index}" aria-pressed="${session.selected===index}" ${f?'disabled':''}><span class="answer-letter">${String.fromCharCode(65+i)}</span>${esc(text)}</button>`).join('')}</div>`:
 `<label class="field"><span>Deine Antwort</span><input id="quiz-input" value="${esc(session.input)}" ${q.type==='number'&&q.answer>=0?`inputmode="${Number.isInteger(q.answer)&&!q.tolerance?'numeric':'decimal'}"`:''} autocomplete="off" spellcheck="false" maxlength="${q.type==='regex'?120:1000}" placeholder="${q.type==='set'?exampleLetters?'Zum Beispiel: {ε, a, ab} oder ∅':'Zum Beispiel: {ε, 0, 01} oder ∅':q.type==='regex'?exampleLetters?'Zum Beispiel: (a|b)*':'Zum Beispiel: (0|1)*':'Dein Ergebnis'}" aria-describedby="quiz-input-help" ${f?'disabled':''}></label>${symbols.length&&!f?symbolKeyboard('quiz-input',symbols,true):''}`}
 <div class="quiz-controls quiz-actions">${actions}</div>
 <div id="quiz-error" role="status"></div>
 ${f?`<div class="feedback ${f.correct?'':'error'}" role="status"><strong>${f.correct?session.hint?'Richtig mit Unterstützung.':'✓ Richtig gelöst.':boss?`Treffer vom Boss. Noch ${session.lives} Leben.`:'Noch nicht ganz. Hier ist der Lösungsweg.'}${f.xp?` <span class="xp-pop">+${f.xp} XP</span>`:''}</strong>${esc(q.explanation)}${f.counter?`<p>${esc(f.counter)}</p>`:''}${!f.correct?`<p><strong>Richtige Antwort: ${esc(answerText(q))}</strong></p>`:''}<p class="help">${f.saved?'✓ Antwort auf diesem Gerät gespeichert.':'Speichern nicht möglich. Bitte exportiere deinen Lernstand.'}${session.hint?' Mit Hilfe geübt – für den Aufgabenhaken noch einmal ohne Hilfe lösen.':''}</p>${lessonById[q.lesson]?`<p class="completed-stamp">${p.completed?'✓ Lektion abgeschlossen':`Noch ${p.remaining} verschiedene richtige Aufgaben ohne Hilfe bis zum Lektionshaken.`}</p>`:''}</div>`:''}
 ${f?questionDfaFeedback(q,esc,'training'):''}
 ${shown?`<div class="training-hints" aria-live="polite">${hints.slice(0,shown).map((h,i)=>`<section class="feedback info"><strong>${i+1}. ${esc(h.title)}</strong><p>${esc(h.text)}</p></section>`).join('')}<p class="help">Mit geöffneter Hilfe zählt diese Antwort als Übung. Für einen selbstständigen Nachweis löst du sie später noch einmal ohne Hilfe.</p></div>`:''}
 ${f&&session.explain?explainPanel(q):''}
 ${q.type!=='choice'?`<p class="help input-help" id="quiz-input-help">${q.type==='set'?'Reihenfolge und doppelte Einträge sind egal. ε, eps oder epsilon stehen für das leere Wort.':q.type==='regex'?'Gleichwertige Ausdrücke sind erlaubt. Die App prüft die vollständige Sprache.':q.type==='number'?`Dezimalstellen mit Komma oder Punkt. ${q.tolerance?`Rundungsabweichungen bis ±${q.tolerance} werden akzeptiert.`:''}`:'Gib das vollständige Wort ein. Für das leere Wort verwende ε.'} Mit Enter prüfen.</p>`:''}
 ${isCheck?'<p class="help input-help">Im Wochencheck erscheinen Lösungen und Bewertung erst am Ende.</p>':''}
 </section></div>`;
}
