const auto=(id,topic,section,points,type,prompt,answer,solution,extra={})=>({id,topic,section,points,type,prompt,answer,solution,...extra});
const open=(id,topic,section,prompt,rubric,solution)=>({id,topic,section,type:'open',prompt,rubric:rubric.map(([points,text])=>({points,text})),points:rubric.reduce((s,[p])=>s+p,0),solution});
export const week2Exam={
 id:'week2-check',title:'Wochencheck · Woche 2',subtitle:'NEA, Minimierung & Darstellungen',kind:'week',points:40,suggestedMinutes:60,
 description:'Die Varianten A1/A3 und B1-B4 aus dem Skript. 60 Minuten als eigener Trainingsrahmen. Geschlossene Fragen werden automatisch geprüft; freie Lösungswege bewertest du nach der Abgabe selbst. Bereits gelesene Lösungen machen den Durchlauf zu einer Wiederholung.',
 questions:[
  auto('powerset','nea','1 · Potenzmenge',1,'number','Q={s,u,f}. Wie viele Elemente besitzt P(Q)?',8,'Jeder der drei Zustände kann enthalten sein oder fehlen: 2³=8.'),
  open('accepting-subsets','nea','1 · Potenzmenge','Q={s,u,f}, F={f}. Liste P(Q) sowie alle darin akzeptierenden Teilmengen auf. Warum müssen nicht alle Teilmengen im Potenzmengen-DEA erreichbar sein?',[[2,'Alle vier akzeptierenden Teilmengen: {f}, {s,f}, {u,f}, {s,u,f}.'],[1,'P(Q) vollständig aufgelistet und die Abhängigkeit der Erreichbarkeit von Start und Übergängen erklärt.']], 'P(Q)={∅,{s},{u},{f},{s,u},{s,f},{u,f},{s,u,f}}. Akzeptierend sind die vier Mengen mit f. Welche Mengen tatsächlich erreichbar sind, ergibt sich erst aus Start und Übergängen.'),
  auto('nfa-start','nea','2 · Determinisieren',2,'set','NEA: Σ={0,1}, Start s, F={f}. ε: s→u; Zeichen: u:0→u,1→v; v:0→f; f:0→f,1→f. Alle übrigen Übergänge leer. Welche Startmenge hat der äquivalente DEA?',['s','u'],'Die ε-Hülle enthält s selbst und den ε-Nachfolger u.'),
  open('nfa-table','nea','2 · Determinisieren','Derselbe NEA: Start s, F={f}; s:ε→u; u:0→u,1→v; v:0→f; f:0→f,1→f; Rest leer. Konstruiere die vollständige erreichbare DEA-Tabelle (vor Minimierung), markiere Endzustände, beschreibe die Sprache und begründe die Konstruktion.',[[5,'Alle fünf Mengen und zehn Übergänge korrekt: A={s,u}, B={u}, C={v}, D={f}, X=∅; 1 P pro vollständiger Zeile.'],[1,'Genau D als akzeptierend markiert.'],[2,'Sprache 0*10(0∪1)* korrekt beschrieben; 1 P für Vorlauf und Pflichtblock, 1 P für beliebige Fortsetzung.'],[2,'Mengeninvariante (1 P) und Annahme über enthaltenen Endzustand (1 P) begründet.']], 'A:0→B,1→C; B:0→B,1→C; C:0→D,1→X; D:0→D,1→D; X:0→X,1→X. Start A, F={D}. Sprache 0*10(0∪1)*. Jede Menge speichert genau die nach dem gelesenen Präfix möglichen NEA-Zustände. Akzeptanz gilt genau bei enthaltenem f.'),
  auto('unreachable','minimize','3 · Minimieren',2,'set','DEA über {0,1}, Start A, F={D,E}. (0,1)-Ziele: A:(B,C); B:(B,D); C:(B,E); D:(B,D); E:(B,E); U:(U,U). Welche Zustände sind unerreichbar?',['U'],'A ist Start, B durch 0, C durch 1, D durch 01 und E durch 11 erreichbar. Nach U führt kein Weg vom Start.'),
  open('minimize','minimize','3 · Minimieren','Minimiere denselben DEA: Start A, F={D,E}; A:(B,C), B:(B,D), C:(B,E), D:(B,D), E:(B,E), U:(U,U) für (0,1). Dokumentiere Partitionen bis zur Stabilität, den Quotientenautomaten mit Start/Endmarkierung und ein Restwort, das A von B trennt.',[[4,'P0={D,E}|{A,B,C}, P1={D,E}|{A}|{B,C}, nächste Runde stabil: 1 P für P0, 2 P für die Verfeinerung, 1 P für begründete Stabilität.'],[4,'Quotient S={A}, N={B,C}, F={D,E}: vollständige Zeilen S:(N,N), N:(N,F), F:(N,F), je 1 P; Start S und Endmenge {F}, 1 P.'],[2,'Zeuge 1 genannt (1 P) und verschiedene Annahme aus A/B nachgewiesen (1 P).']], 'U entfernen. P0={D,E}|{A,B,C}; P1={D,E}|{A}|{B,C}; stabil. S={A}, N={B,C}, F={D,E}. S:0→N,1→N; N:0→N,1→F; F:0→N,1→F. Start S, akzeptierend F. Restwort 1: A→C lehnt ab, B→D akzeptiert.'),
  auto('regex','regular-grammar','4 · Übersetzen',2,'regex','RegEx über {a,b}: Das Wort beginnt mit b und enthält mindestens ein a.','bb*a(a|b)*','Mindestens ein b vor dem ersten a; nach diesem a ist alles erlaubt.',{alphabet:['a','b']}),
  open('grammar','regular-grammar','4 · Übersetzen','Gib eine rechtslineare Grammatik für „beginnt mit b und enthält mindestens ein a“ über {a,b} an. Nenne Start und Variablen und leite bbab ab.',[[4,'Grammatik korrekt: erster Buchstabe b (1 P), verpflichtendes a vor Abschluss (1 P), beliebige Fortsetzung (1 P), Start/Variablen und rechtslineare Form (1 P).'],[2,'Vollständige korrekte Ableitung von bbab einschließlich Abschluss.']], 'Σ={a,b}, V={S,A,B}, Start S. S→bA; A→bA|aB; B→aB|bB|ε. S⇒bA⇒bbA⇒bbaB⇒bbabB⇒bbab.'),
  open('kleene','kleene','5 · Begründen','Erkläre beide Richtungen des Satzes von Kleene. Nenne je ein geeignetes allgemeines Übersetzungsverfahren.',[[1,'RegEx→ε-NEA mit Grundbausteinen/Operationen, danach Potenzmengenkonstruktion zum DEA.'],[1,'DEA→RegEx durch Zustandselimination bzw. systematisches Zusammenfassen der Wege.']], 'RegEx→ε-NEA durch strukturellen Aufbau; NEA→DEA durch Potenzmenge. DEA→RegEx durch Zusammenfassen direkter Wege und Wege über Zwischenzustände. So werden beide Inklusionsrichtungen gezeigt.'),
  open('complement','kleene','5 · Begründen','NEA über {0}: Start s, F={f}, δ(s,0)={s,f}, Rest leer. Warum liefert F↦{s} kein Komplement? Belege es mit 0 und nenne den richtigen Weg.',[[1,'0 wird vorher über s→f und nachher über s→s akzeptiert; konkreter Gegenbeleg.'],[1,'Determinisieren, vollständigen DEA sicherstellen, dann Endzustände invertieren.']], 'Beide Automaten akzeptieren 0, aber im Komplement müsste es abgelehnt werden. Vorher akzeptiert der Lauf nach f, nachher der Lauf nach s. Richtig: Potenzmengenkonstruktion, Vervollständigung, F durch Q∖F ersetzen.')
 ]
};
