import {week2Content,week2ChapterById} from './week2-content.js';
import {epsilonClosure,nfaStep,determinize,minimize} from './algorithms.js';
import {suffixNfa,exercise6Nfa,exercise7Dfa,examDfa,nfaLabel} from './week2-models.js';

export const week2Topics=['nea','minimize','regular-grammar','kleene'];
const topicTitles=['NEA & Potenzmenge','Minimierung','Reguläre Grammatiken','Satz von Kleene'];
export const week2Ui={example:'suffix',word:'0010',position:0,error:'',minExample:'original7',round:0};
const models={suffix:suffixNfa,original6:exercise6Nfa};
const dfaModels={original7:exercise7Dfa,variant:examDfa};
const pdfPath='./assets/Lernskript_Woche_2_Theoretische_Informatik.pdf';
export const week2Progress=(state,questions)=>week2Topics.map((id,i)=>({id,title:topicTitles[i],solved:questions.filter(q=>q.lesson===id&&state.results[q.id]?.successes.length).length,total:questions.filter(q=>q.lesson===id).length}));
const table=(columns,rows,esc,caption='')=>`<div class="table-scroll w2-table" tabindex="0" role="region" aria-label="${esc(caption||columns.join(', '))}"><table>${caption?`<caption>${esc(caption)}</caption>`:''}<thead><tr>${columns.map(c=>`<th scope="col">${esc(c)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
function block(b,esc){
 if(b.type==='table')return table(b.columns,b.rows,esc);
 if(b.type==='steps')return `<ol class="method-recipe">${b.items.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`;
 if(b.type==='callout')return `<div class="callout w2-callout"><strong>${esc(b.title)}</strong><p>${esc(b.text)}</p></div>`;
 if(b.type==='checkpoint')return `<section class="w2-recall"><h3>Stopp · selbst erklären</h3><p>${esc(b.prompt)}</p><details class="solution-reveal"><summary>Antwort vergleichen</summary><p>${esc(b.answer)}</p></details></section>`;
 return `<p>${esc(b.text)}</p>`;
}
export function week2Card(state,questions,esc){
 const progress=week2Progress(state,questions),read=state.week2?.read||[];
 return `<section class="card w2-entry"><div><span class="pill">WOCHE 02 · VOLLSTÄNDIGES SKRIPT</span><h2>Von Möglichkeiten zu klaren Zuständen.</h2><p>10 Kapitel · durchgerechnete Originalaufgaben · zwei Labore · 40-Punkte-Wochencheck</p><p class="help">${read.length}/10 Kapitel als gelesen markiert · ${progress.filter(p=>p.solved>=7).length}/4 Themen mit mindestens sieben selbstständig gelösten Aufgaben</p></div><div class="inline-actions"><a class="btn" href="#week2">Woche 2 öffnen →</a><a class="btn secondary" href="${pdfPath}" download>PDF herunterladen</a></div></section>`;
}
export function week2View(id,{state,questions,esc}){
 if(id&&!Object.hasOwn(week2ChapterById,id))return `<section class="card"><h1>Kapitel nicht gefunden</h1><a class="btn" href="#week2">Zur Übersicht</a></section>`;
 const c=week2ChapterById[id],read=state.week2?.read||[],last=state.week2?.lastChapter||'grundlagen';
 const toc=week2Content.chapters.map(ch=>`<a href="#week2/${ch.id}" ${ch.id===id?'aria-current="page"':''}><span aria-hidden="true">${read.includes(ch.id)?'✓':'○'}</span><span>${esc(ch.title)}</span></a>`).join('');
 const actions=`<div class="inline-actions w2-resources"><a class="btn secondary" href="${pdfPath}" download>PDF herunterladen</a><a class="btn secondary" href="#week2-lab">Automatenlabore</a><button class="btn secondary" data-action="exam-start" data-id="week2-check">Wochencheck starten</button></div>`;
 if(!c)return `<a class="back-link" href="#path">← Zum Lernpfad</a><header class="w2-header"><div class="eyebrow">28.09. - 04.10.2026 · 8 STUNDEN</div><h1>${esc(week2Content.title)}</h1><p class="lead">${esc(week2Content.subtitle)}</p><p>${esc(week2Content.introduction)}</p><div class="inline-actions"><a class="btn" href="#week2/${last}">${read.length?'Im Skript weiterlesen':'Mit den Grundlagen starten'} →</a></div>${actions}</header>
 <div class="w2-layout"><article class="reading"><section class="card"><h2>Deine fünf Lernziele</h2><ul class="topic-steps">${week2Content.goals.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="reading-section"><h2>Kapitel und Lesefortschritt</h2><nav class="w2-chapters" aria-label="Skriptkapitel">${toc}</nav><p class="help">Lesemarkierungen sind keine Wissensnachweise. Für den Pokal löst du in jedem der vier Themen sieben verschiedene Aufgaben ohne Hilfe.</p></section><section class="reading-section"><h2>Deine Woche in acht Stunden</h2>${table(['Tag','Zeit','Arbeitsauftrag'],week2Content.plan,esc,'Lernplan Woche 2')}</section><details class="solution-reveal"><summary>Quellen und Fundstellen</summary>${table(['Unterlage','Fundstelle','Bezug'],week2Content.sources,esc)}</details></article><aside class="stack w2-side"><section class="card"><h2>Dein Übungsstand</h2>${week2Progress(state,questions).map(p=>`<a class="lesson-row" href="#practice/${p.id}"><div><h3>${p.solved>=7?'✓ ':''}${esc(p.title)}</h3><p>${p.solved}/${p.total} Aufgaben ohne Hilfe gelöst</p></div><span aria-hidden="true">→</span></a>`).join('')}<button class="btn full" data-action="w2-training">12 gemischte Aufgaben</button></section><section class="card"><h2>Wissen ausprobieren</h2><p>Schau zu, wie alle möglichen NEA-Zustände mitwandern. Verfolge danach, warum eine Gruppe beim Minimieren zerfällt.</p><a class="btn secondary" href="#week2-lab">Zu den Laboren →</a></section><section class="card"><h2>Wochencheck</h2><p>40 Punkte, optional 60 Minuten. Freie Lösungswege bewertest du nach der Abgabe anhand des Rasters selbst.</p><label class="field">Zeitrahmen<select id="duration-week2-check"><option value="60">60 Minuten</option><option value="0">Ohne Zeitlimit</option></select></label><button class="btn" data-action="exam-start" data-id="week2-check">Check starten →</button></section></aside></div>`;
 const index=week2Content.chapters.indexOf(c),next=week2Content.chapters[index+1],previous=week2Content.chapters[index-1];
 return `<a class="back-link" href="#week2">← Woche 2 · Übersicht</a><header class="w2-header"><div class="eyebrow">KAPITEL ${index+1} VON 10 · CA. ${c.minutes} MINUTEN MIT EIGENER RECHNUNG</div><h1>${esc(c.title)}</h1><div class="learning-goal"><strong>Danach kannst du:</strong><p>${esc(c.goal)}</p></div></header>
 <details class="w2-mobile-toc"><summary>Kapitel wechseln</summary><nav class="w2-chapters" aria-label="Mobile Kapitelnavigation">${toc}</nav></details>
 <div class="w2-layout"><article class="reading w2-reader">${c.solutions?'<div class="callout"><strong>Erst selbst lösen</strong><p>Dieses Kapitel enthält die Vergleichslösungen. Bearbeite die Aufgaben aus Kapitel 8 vor dem Aufdecken.</p></div><details class="solution-reveal w2-solutions"><summary>Vergleichslösungen aufdecken</summary>':''}${c.pages.map(page=>`<section class="reading-section"><h2>${esc(page.title)}</h2>${page.blocks.map(b=>block(b,esc)).join('')}</section>`).join('')}${c.solutions?'</details>':''}<section class="card w2-chapter-end"><h2>Dein nächster Schritt</h2><button class="btn secondary" data-action="w2-read" data-id="${c.id}" aria-pressed="${read.includes(c.id)}">${read.includes(c.id)?'✓ Gelesen · Markierung entfernen':'Kapitel als gelesen markieren'}</button><p class="help" id="w2-save-status" role="status">Die Lesemarkierung zählt keine XP und ersetzt keine gelöste Aufgabe.</p><div class="inline-actions"><a class="btn" href="#practice/${c.topic}">Passende Aufgaben üben →</a><a class="btn secondary" href="#week2-lab">Im Labor ausprobieren</a></div><div class="w2-pagination">${previous?`<a href="#week2/${previous.id}">← ${esc(previous.title)}</a>`:'<span></span>'}${next?`<a href="#week2/${next.id}">${esc(next.title)} →</a>`:'<a href="#week2">Zur Wochenübersicht →</a>'}</div></section></article><aside class="w2-side"><nav class="card w2-chapters sticky" aria-label="Skriptkapitel">${toc}<a href="${pdfPath}" download>↓ Das ganze Skript als PDF</a></nav></aside></div>`;
}
export function week2LabView({esc}){
 const ui=week2Ui,nfa=models[ui.example],dfa=dfaModels[ui.minExample];
 let states=epsilonClosure(nfa,[nfa.start]);const history=[['ε',nfaLabel(states)]];
 for(const symbol of ui.word.slice(0,ui.position)){states=nfaStep(nfa,states,symbol);history.push([ui.word.slice(0,history.length),nfaLabel(states)]);}
 const end=ui.position===ui.word.length,accepted=states.some(s=>nfa.accept.includes(s)),rows=determinize(nfa),m=minimize(dfa),round=Math.min(ui.round,m.rounds.length),partition=m.rounds[Math.min(round,m.rounds.length-1)];
 const label=(s)=>`${s===nfa.start?'→ ':''}${nfa.accept.includes(s)?'* ':''}${s}`;
 const stepText=end?`Wort vollständig gelesen: ${accepted?'angenommen':'abgelehnt'}.`:`${ui.position} von ${ui.word.length} Zeichen gelesen. ${accepted?'Momentan ist ein Endzustand dabei. Die übrigen Zeichen müssen noch gelesen werden.':'Noch keine endgültige Wortentscheidung.'}`;
 return `<a class="back-link" href="#week2">← Zum Skript Woche 2</a><header class="w2-header"><div class="eyebrow">VERSTEHEN DURCH AUSPROBIEREN</div><h1>Deine Automatenlabore</h1><p>Verändere das Wort, gehe einzelne Schritte und erkläre die nächste Zustandsmenge zuerst selbst. Die Labore vergeben keine Wissenspunkte.</p></header>
 <section class="card w2-lab" id="w2-nfa-lab"><h2>1 · NEA-Lauf & Potenzmenge</h2><div class="w2-controls"><label class="field">Beispiel<select data-w2-select="nfa"><option value="suffix" ${ui.example==='suffix'?'selected':''}>Binärwörter mit Endung 01</option><option value="original6" ${ui.example==='original6'?'selected':''}>Originalaufgabe 6 · ε-NEA</option></select></label><label class="field">Wort über {${nfa.alphabet.join(',')}} · leer lassen für ε<input id="w2-word" maxlength="24" autocomplete="off" spellcheck="false" value="${esc(ui.word)}"></label><button class="btn secondary" data-action="w2-word">Wort übernehmen</button></div>
 <div class="symbol-keyboard w2-keyboard" aria-label="Zeichen anhängen">${nfa.alphabet.map(c=>`<button class="symbol-key" data-action="w2-symbol" data-symbol="${c}" aria-label="${c} ans Eingabewort anhängen">${c}</button>`).join('')}<button class="symbol-key" data-action="w2-empty">ε · Wort leeren</button></div><p class="feedback error" id="w2-word-error" role="alert" ${ui.error?'':'hidden'}>${esc(ui.error)}</p>
 ${table(['Zustand',...nfa.alphabet,'ε'],nfa.states.map(s=>[label(s),...nfa.alphabet.map(a=>nfaLabel(nfa.transitions[s]?.[a]||[])),nfaLabel(nfa.transitions[s]?.['']||[])]),esc,'NEA-Übergänge · → Start, * akzeptierend')}
 <div class="w2-active-states" aria-label="Mögliche NEA-Zustände">${nfa.states.map(s=>`<div class="w2-state ${states.includes(s)?'is-active':''} ${nfa.accept.includes(s)?'is-final':''}"><strong>${esc(s)}</strong><span>${states.includes(s)?'möglich':'inaktiv'}${nfa.accept.includes(s)?' · Endzustand':''}</span></div>`).join('')}</div>
 <p class="w2-word-display" aria-label="Gelesenes Wort"><mark>${esc(ui.word.slice(0,ui.position))}</mark><span>${esc(ui.word.slice(ui.position))}</span>${!ui.word?'ε':''}</p><p role="status" id="w2-run-status"><strong>${esc(nfaLabel(states))}</strong> · ${esc(stepText)}</p><div class="inline-actions"><button class="btn secondary" data-action="w2-back" ${ui.position===0?'disabled':''}>← Schritt zurück</button><button class="btn" data-action="w2-step" ${end?'disabled':''}>Nächstes Zeichen →</button><button class="btn ghost" data-action="w2-reset">Zum Start</button></div>
 ${table(['Gelesenes Präfix','Zustandsmenge nach ε-Hülle'],history,esc,'Dein bisheriger Lauf')}
 <details class="solution-reveal"><summary>Vollständigen Potenzmengen-DEA vergleichen</summary>${table(['Zustandsmenge',...nfa.alphabet,'Akzeptiert?'],rows.map(r=>[nfaLabel(r.states),...nfa.alphabet.map(a=>nfaLabel(r.next[a])),r.accept?'ja':'nein']),esc)}<p>${rows.length} erreichbare von höchstens ${2**nfa.states.length} möglichen Mengen. Die erste Zeile ist der Startzustand.</p></details></section>
 <section class="card w2-lab" id="w2-min-lab"><h2>2 · Minimierung Runde für Runde</h2><label class="field">Beispiel<select data-w2-select="min"><option value="original7" ${ui.minExample==='original7'?'selected':''}>Originalaufgabe 7 · acht Zustände</option><option value="variant" ${ui.minExample==='variant'?'selected':''}>Neue Variante B1 · unerreichbarer Zustand</option></select></label>
 ${table(['Zustand',...dfa.alphabet],dfa.states.map(s=>[`${s===dfa.start?'→ ':''}${dfa.accept.includes(s)?'* ':''}${s}`,...dfa.alphabet.map(a=>dfa.transitions[s][a])]),esc,'Vollständiger DEA')}
 <p><strong>Erreichbarkeit:</strong> ${m.unreachable.length?`${m.unreachable.join(', ')} ist unerreichbar und wird zuerst entfernt.`:'Alle Zustände sind vom Start erreichbar.'}</p>
 <div id="w2-partition" role="status"><h3>${round===m.rounds.length?'Stabilität bestätigt':`Partition P${round}`}</h3><div class="w2-groups">${partition.map((g,i)=>`<div class="w2-group"><strong>G${i+1}</strong><span>${esc(nfaLabel(g))}</span></div>`).join('')}</div><p>${round===m.rounds.length?`Keine weitere Trennung. Der minimale vollständige DEA hat ${partition.length} Zustände.`:round===0?'Zunächst Endzustände von Nichtendzuständen trennen. Welche Zustände gelangen mit einem Zeichen in unterschiedliche Gruppen?':'Jede Gruppe der letzten Runde wurde nach ihren Zielgruppen aufgeteilt. Prüfe nun erneut alle Alphabetzeichen.'}</p></div>
 <details class="solution-reveal"><summary>Zielsignaturen der aktuellen Partition</summary>${table(['Zustand',...dfa.alphabet.map(a=>`Zielgruppe bei ${a}`)],partition.flatMap(g=>g.map(s=>[s,...dfa.alphabet.map(a=>`G${partition.findIndex(group=>group.includes(dfa.transitions[s][a]))+1}`)])),esc)}<p>Vergleiche Signaturen nur innerhalb desselben bisherigen Blocks. Verwende während einer Runde immer dieselbe alte Partition.</p></details>
 <div class="inline-actions"><button class="btn secondary" data-action="w2-min-back" ${round===0?'disabled':''}>← Runde zurück</button><button class="btn" data-action="w2-min-next" ${round===m.rounds.length?'disabled':''}>${round===m.rounds.length-1?'Stabilität prüfen':'Nächste Verfeinerung'} →</button><button class="btn ghost" data-action="w2-min-reset">Neu beginnen</button></div>
 ${round===m.rounds.length?table(['Quotientenklasse',...dfa.alphabet],partition.map((g,i)=>[`${g.includes(dfa.start)?'→ ':''}${g.some(s=>dfa.accept.includes(s))?'* ':''}G${i+1}=${nfaLabel(g)}`,...dfa.alphabet.map(a=>`G${partition.findIndex(group=>group.includes(dfa.transitions[g[0]][a]))+1}`)]),esc,'Minimaler vollständiger DEA'):''}
 <a class="btn secondary" href="#practice/minimize">Jetzt ohne Vorlage üben →</a></section>`;
}
export function setWeek2Word(input){
 const word=input.replace(/\s/g,'').replace(/^ε$/,'');
 if(word.length>24||[...word].some(c=>!models[week2Ui.example].alphabet.includes(c))){week2Ui.error=`Nutze höchstens 24 Zeichen aus {${models[week2Ui.example].alphabet.join(',')}} oder ε.`;return false;}
 week2Ui.word=word;week2Ui.position=0;week2Ui.error='';return true;
}
export function week2LabAction(action){
 const u=week2Ui;
 if(action==='w2-step')u.position=Math.min(u.word.length,u.position+1);
 if(action==='w2-back')u.position=Math.max(0,u.position-1);
 if(action==='w2-reset')u.position=0;
 if(action==='w2-min-next')u.round=Math.min(minimize(dfaModels[u.minExample]).rounds.length,u.round+1);
 if(action==='w2-min-back')u.round=Math.max(0,u.round-1);
 if(action==='w2-min-reset')u.round=0;
}
